import { PromptPost } from './types';

export const aiWebDesignPrompts: PromptPost = {
  slug: 'ai-web-design-prompts',
  title: 'AI Prompts for Expert Web Design: 50+ Pro Prompts (2026)',
  keyword: 'ai web design prompts',
  description: 'Create stunning websites with these expert AI prompts. Pro-level results for any web project.',
  date: '2026-04-21',
  category: 'Web Design',
  image: '/images/ai-web-design-prompts.jpg',
  content: `<p>Use these <strong>expert web design prompts</strong> to create professional websites with AI assistance.</p>`,
  shortPrompts: [
    { id: 'web-1', prompt: 'Create a minimalist SaaS landing page hero section. Headline, subheadline, CTA. Clean aesthetic.', description: 'SaaS Hero' },
    { id: 'web-2', prompt: 'Design an ecommerce product page. Product image, price, add to cart, reviews.', description: 'Product Page' },
    { id: 'web-3', prompt: 'Create about us page for a startup. Mission, team, values. Professional.', description: 'About Page' },
    { id: 'web-4', prompt: 'Design a contact form. Fields, submit button, map integration.', description: 'Contact Form' },
    { id: 'web-5', prompt: 'Create navigation header. Logo, menu items, mobile hamburger.', description: 'Nav Header' },
    { id: 'web-6', prompt: 'Design feature comparison Pricing table. 3 tiers, popular badge.', description: 'Pricing Table' },
    { id: 'web-7', prompt: 'Create blog post layout. Title, author, content, related posts.', description: 'Blog Layout' },
    { id: 'web-8', prompt: 'Design testimonial section. Quote, photo, name, company.', description: 'Testimonials' },
    { id: 'web-9', prompt: 'Create footer. Links, social, newsletter signup.', description: 'Footer' },
    { id: 'web-10', prompt: 'Design hero for portfolio. Large image, case studies, contact CTA.', description: 'Portfolio Hero' },
    { id: 'web-11', prompt: 'Create FAQ accordion. Questions, expandable answers.', description: 'FAQ Section' },
    { id: 'web-12', prompt: 'Design team page. Photos, bios, social links.', description: 'Team Page' },
    { id: 'web-13', prompt: 'Create coming soon page. Email capture, countdown.', description: 'Coming Soon' },
    { id: 'web-14', prompt: 'Design login/signup page. Email, password, social login options.', description: 'Auth Page' },
    { id: 'web-15', prompt: 'Create dashboard layout. Sidebar, header, main content area.', description: 'Dashboard' },
    { id: 'web-16', prompt: 'Design 404 error page. Illustration, link home.', description: '404 Page' },
    { id: 'web-17', prompt: 'Create feature grid. Icon, title, description per feature.', description: 'Features Grid' },
    { id: 'web-18', prompt: 'Design services section. Cards with icons, descriptions.', description: 'Services' },
    { id: 'web-19', prompt: 'Create CTA banner. Headline, button, background.', description: 'CTA Section' },
    { id: 'web-20', prompt: 'Design mobile menu. Full screen, animated links.', description: 'Mobile Menu' },
    { id: 'web-21', prompt: 'Create stats counter. Numbers, labels, animation ready.', description: 'Stats' },
    { id: 'web-22', prompt: 'Design image gallery. Grid, lightbox ready.', description: 'Gallery' },
    { id: 'web-23', prompt: 'Create job listing page. Position, apply button, details.', description: 'Careers' },
    { id: 'web-24', prompt: 'Design cookie consent. Banner, accept options.', description: 'Cookies' },
    { id: 'web-25', prompt: 'Create email confirmation page. Success message, next steps.', description: 'Confirmation' }
  ],
  longPrompts: [
    { id: 'web-long-21', title: 'Complete Startup Website', prompt: 'Create full startup website: hero with value prop, 3-column features, testimonial carousel, pricing table, team grid, contact form, footer. Conversions-focused. Professional SaaS aesthetic with clear CTAs.', useCase: 'Startup Site' },
    { id: 'web-long-2', title: 'Ecommerce Storefront', prompt: 'Create ecommerce home: hero with rotating banner, category grid (6 items), featured products (8 items), best sellers, newsletter signup, footer. Shopping-focused with clear navigation and cart indicator.', useCase: 'Ecommerce' },
    { id: 'web-long-3', title: 'Restaurant Website', prompt: 'Create restaurant site: hero with food video background, about story, menu by category, reservations form, gallery, reviews, location/map, hours, contact. Warm, appetizing design.', useCase: 'Restaurant' },
    { id: 'web-long-4', title: 'Portfolio Website', prompt: 'Create portfolio: bold hero with work, filterable case studies grid, about section, services list, client logos, testimonial slider, contact form. Show, don\'t tell. Visual-first.', useCase: 'Portfolio' },
    { id: 'web-long-5', title: 'Membership Site', prompt: 'Create membership: hero explaining value, benefits grid (8 items), pricing tiers, FAQ, testimonials, guarantee, CTA. Trust-building with clear upgrade path.', useCase: 'Membership' },
    { id: 'web-long-6', title: 'Course Platform', prompt: 'Create course site: hero with course preview, curriculum accordion, instructor bio, student outcomes, pricing, enrollment CTA, guarantee. Learning-focused.', useCase: 'Course' },
    { id: 'web-long-7', title: 'Agency Website', prompt: 'Create agency: bold hero, case studies (filterable), services list, process steps, team grid, clients logos, contact. Trust and results-focused.', useCase: 'Agency' },
    { id: 'web-long-8', title: 'Mobile App Landing', prompt: 'Create mobile app landing: app preview mockups, features by OS, App Store badges, testimonials, CTA. Clear download path. App-centric design.', useCase: 'Mobile App' },
    { id: 'web-long-9', title: 'Real Estate Site', prompt: 'Create real estate: search interface, property cards grid, map integration, agent profiles, valuations, neighborhoods. Property-focused with search.', useCase: 'Real Estate' },
    { id: 'web-long-10', title: 'Healthcare Website', prompt: 'Create medical practice: services overview, team credentials, patient testimonials, insurance accepted, appointment form, emergency banner. Trust and care-focused.', useCase: 'Healthcare' },
    { id: 'web-long-11', title: 'Nonprofit Website', prompt: 'Create nonprofit: mission statement, impact metrics, programs grid, donate CTA, volunteer section, events, stories. Emotional connection with clear giving path.', useCase: 'Nonprofit' },
    { id: 'web-long-12', title: 'SaaS Pricing Page', prompt: 'Create comprehensive pricing: toggle (monthly/yearly), 4 tiers with features comparison, FAQ, enterprise contact, satisfaction guarantee. Clear decision path.', useCase: 'Pricing' },
    { id: 'web-long-13', title: 'Webinar Registration', prompt: 'Create webinar page: speaker info, topic breakdown, date/time, what attendees learn (5+ takeaways), testimonials, registration form. Urgency and value-focused.', useCase: 'Webinar' }
  ],
  faqs: [
    { question: 'Which AI tools create website UI?', answer: 'v0 by Vercel for React. Figma AI for designs. Bookmark for AI building. Combine with custom prompts.' },
    { question: 'Can AI generate functional code?', answer: 'Yes! v0, Lovable, and others generate working React/Vue from prompts. Requires review.' },
    { question: 'What makes good web design prompts?', answer: 'Be specific: layout, colors, behavior. Include "responsive", "animations", "accessibility".' },
    { question: 'How do I get consistent designs?', answer: 'Provide style guide. Reference other sites. Use same system prompts.' },
    { question: 'Can AI create responsive designs?', answer: 'Specify mobile-first. Request responsive behavior. Test outputs across breakpoints.' },
    { question: 'How do I add animations?', answer: 'Request smooth animations, micro-interactions, scroll effects. Add after base design.' },
    { question: 'Can AI create dark mode?', answer: 'Request both versions. Include dark mode and light mode in prompts.' },
    { question: 'How do I improve AI outputs?', answer: 'Iterate on successful designs. Be specific about changes. Reference successful patterns.' }
  ],
  platformTips: [
    'Be specific: "modern minimalist" not "good design"',
    'Include brand colors: "green (#00FF00) accent"',
    'Specify: "responsive/mobile-first"',
    'Add: "accessibility compliant" for a11y',
    'Request: "loading states and empty states"',
    'Include: "hover states and focus states"',
    'Specify: "dark mode ready" for theming',
    'Iterate: reference good outputs'
  ]
};