import { PromptPost } from './types';

export const artPromptGenerator: PromptPost = {
  slug: 'art-prompt-generator',
  title: 'Art Prompt Generator: 50+ Creative AI Image Prompts (2026)',
  keyword: 'art prompt generator',
  description: 'Generate stunning AI art with our creative prompt generator. 50+ prompts for Midjourney, DALL-E, and Stable Diffusion.',
  date: '2026-04-21',
  category: 'Image Generation',
  image: '/images/art-prompt-generator.jpg',
  content: `<p>Use these creative <strong>art prompts</strong> with Midjourney, DALL-E, or Stable Diffusion to generate amazing AI artwork.</p>`,
  shortPrompts: [
    { id: 'art-1', prompt: '/imagine prompt: neon city skyline at night, rain-slicked streets, reflections, cyberpunk --ar 16:9 --v 6', description: 'Neon cyberpunk city' },
    { id: 'art-2', prompt: '/imagine prompt: underwater temple, ancient ruins, glowing fish, mist --ar 16:9 --v 6', description: 'Underwater ruins' },
    { id: 'art-3', prompt: '/imagine prompt: steampunk airship, clouds, brass details, Victorian --ar 16:9 --v 6', description: 'Steampunk airship' },
    { id: 'art-4', prompt: '/imagine prompt: bioluminescent forest, glowing mushrooms, fantasy --ar 16:9 --v 6', description: 'Magic forest' },
    { id: 'art-5', prompt: '/imagine prompt: floating island, waterfalls, dreamscape --ar 16:9 --v 6', description: 'Floating paradise' },
    { id: 'art-6', prompt: '/imagine prompt: space station, Earth view, zero gravity --ar 16:9 --v 6', description: 'Space station' },
    { id: 'art-7', prompt: '/imagine prompt: dragon hoard, gold coins, cave lighting --ar 16:9 --v 6', description: 'Dragon treasure' },
    { id: 'art-8', prompt: '/imagine prompt: vintage travel poster, paris, art deco --ar 2:3 --v 6', description: 'Art deco poster' },
    { id: 'art-9', prompt: '/imagine prompt: minimalist flower, soft colors, studio light --ar 3:4 --v 6', description: 'Minimalist bloom' },
    { id: 'art-10', prompt: '/imagine prompt: wild wolf, snowy mountains, dramatic --ar 3:4 --v 6', description: 'Noble wolf' },
    { id: 'art-11', prompt: '/imagine prompt: cottage, autumn, warm colors, smoke --ar 16:9 --v 6', description: 'Autumn cottage' },
    { id: 'art-12', prompt: '/imagine prompt: album cover, electronic music, abstract --ar 1:1 --v 6', description: 'Album art' },
    { id: 'art-13', prompt: '/imagine prompt: book cover, fantasy novel, epic --ar 2:3 --v 6', description: 'Book cover' },
    { id: 'art-14', prompt: '/imagine prompt: cosmic nebula, stars, purple tones, NASA --ar 16:9 --v 6', description: 'Space beauty' },
    { id: 'art-15', prompt: '/imagine prompt: coffee shop, warm interior, rainy window --ar 4:5 --v 6', description: 'Cozy café' },
    { id: 'art-16', prompt: '/imagine prompt: fashion portrait, studio, magazine --ar 3:4 --v 6', description: 'Fashion shoot' },
    { id: 'art-17', prompt: '/imagine prompt: japanese garden, cherry blossoms, zen --ar 16:9 --v 6', description: 'Japanese garden' },
    { id: 'art-18', prompt: '/imagine prompt: abandoned mall, eerie, post-apocalyptic --ar 16:9 --v 6', description: 'Dead mall' },
    { id: 'art-19', prompt: '/imagine prompt:product shot, sneakers, modern, clean --ar 4:5 --v 6', description: 'Product photo' },
    { id: 'art-20', prompt: '/imagine prompt: portrait, elder, wisdom, Rembrandt --ar 3:4 --v 6', description: 'Wise elder' },
    { id: 'art-21', prompt: '/imagine prompt: logo, tech company, minimalist, blue --ar 1:1 --v 6', description: 'Tech logo' },
    { id: 'art-22', prompt: '/imagine prompt: wedding, rings, flowers, romantic --ar 3:4 --v 6', description: 'Wedding rings' },
    { id: 'art-23', prompt: '/imagine prompt: concert, crowd, lights, energy --ar 16:9 --v 6', description: 'Live music' },
    { id: 'art-24', prompt: '/imagine prompt: desert, pyramids, sunset, golden --ar 16:9 --v 6', description: 'Desert sunset' },
    { id: 'art-25', prompt: '/imagine prompt: ice castle, frozen, blue, fantasy --ar 16:9 --v 6', description: 'Ice palace' }
  ],
  longPrompts: [
    { id: 'art-long-1', title: 'Epic Fantasy Landscape', prompt: '/imagine prompt: Massive fantasy kingdom with floating islands connected by bridges, ancient temples, dragons in sky, epic scale, golden hour lighting, concept art by Craig Mullins and Feng Zhu --ar 16:9 --stylize 750 --v 6', useCase: 'Fantasy Concept Art' },
    { id: 'art-long-2', title: 'Luxury Product Photography', prompt: '/imagine prompt: Premium watch on marble, dramatic lighting, luxury brand aesthetic, commercial photography, high-end studio, sharp focus, bokeh background, by product photography masters --ar 4:5 --stylize 250 --v 6', useCase: 'E-commerce' },
    { id: 'art-long-3', title: 'Cinematic Movie Poster', prompt: '/imagine prompt: Action movie poster, hero in trench coat facing explosion, dramatic pose, bold typography space, blockbuster style, cinematic lighting, movie poster quality, by Aaron McGruder --ar 2:3 --stylize 500 --v 6', useCase: 'Film Marketing' },
    { id: 'art-long-4', title: 'Children Book Illustration', prompt: '/imagine prompt: Whimsical children\'s illustration, friendly bear having tea party in forest, soft colors, Quentin Blake style, sweet and enchanting, storybook aesthetic --ar 5:4 --stylize 1000 --v 6', useCase: 'Kids Books' },
    { id: 'art-long-5', title: 'Architectural Visualization', prompt: '/imagine prompt: Modern sustainable home, interior-exterior, floor to ceiling glass, living wall, solar panels, infinity pool, dusk lighting, architectural photography, by Frank Lloyd Wright inspired --ar 16:9 --stylize 500 --v 6', useCase: 'Real Estate' },
    { id: 'art-long-6', title: 'Fashion Editorial', prompt: '/imagine prompt: High fashion editorial, model in avant-garde couture, urban rooftop, golden hour, Vogue style, dramatic lighting, magazine cover quality, by Mario Testino --ar 2:3 --stylize 500 --v 6', useCase: 'Fashion' },
    { id: 'art-long-7', title: 'Sci-Fi Character Design', prompt: '/imagine prompt: Cybernetic warrior, full body, sleek armor, neon accents, cinematic lighting, Star Wars concept art style, by Doug Chiang --ar 3:4 --stylize 750 --v 6', useCase: 'Game Design' },
    { id: 'art-long-8', title: 'Restaurant Food Photography', prompt: '/imagine prompt: Gourmet dish, perfect plating, fresh herbs, rustic table, natural window light, food styling by professional, appetizing, Food Network style --ar 4:5 --stylize 250 --v 6', useCase: 'Restaurant Marketing' },
    { id: 'art-long-9', title: 'Abstract Album Art', prompt: '/imagine prompt: Abstract album art, fluid colors, musical energy, vinyl vibes, gradient, minimal but striking, works at small sizes, club flyer aesthetic --ar 1:1 --stylize 1000 --v 6', useCase: 'Music Marketing' },
    { id: 'art-long-10', title: 'Travel Photography', prompt: '/imagine prompt: Influencer at destination, golden hour, wanderlust, National Geographic adventure style, aspirational travel, professional travel photography --ar 1:1 --stylize 500 --v 6', useCase: 'Social Media' },
    { id: 'art-long-11', title: 'Comic Book Panel', prompt: '/imagine prompt: Comic book action panel, hero vs villain, dynamic pose, inked linework, Marvel Comics style, Frank Miller inspired, dramatic panel --ar 2:3 --stylize 750 --v 6', useCase: 'Comic Art' },
    { id: 'art-long-12', title: 'Wedding Photography', prompt: '/imagine prompt: Elegant wedding photograph, bride in white gown, garden setting, soft natural light, bokeh, timeless romance, by Jose Villa --ar 3:4 --stylize 500 --v 6', useCase: 'Wedding Marketing' },
    { id: 'art-long-13', title: 'Tech Startup Mascot', prompt: '/imagine prompt: Friendly robot mascot for tech company, geometric shapes, gradient blue and green, modern, scalable, works small and large, clever design --ar 1:1 --stylize 500 --v 6', useCase: 'Logo Design' },
    { id: 'art-long-14', title: 'Real Estate Listing', prompt: '/imagine prompt: Modern living room, staged, warm lighting, aspirational lifestyle, wide angle, luxury home aesthetic, Sotheby\'s photography --ar 16:9 --stylize 250 --v 6', useCase: 'Real Estate' },
    { id: 'art-long-15', title: 'Infographic Illustration', prompt: '/imagine prompt: Business infographic, flat design, modern palette, clean vectors, data visualization, corporate presentation quality, suitable for reports --ar 16:9 --stylize 250 --v 6', useCase: 'Business' },
    { id: 'art-long-16', title: 'T-Shirt Design', prompt: '/imagine prompt: Vintage sports t-shirt design, retro athletic logo, 1970s design, bold typography, works as DTG print, limited colors --ar 3:4 --stylize 250 --v 6', useCase: 'Merchandise' },
    { id: 'art-long-17', title: 'Music Festival Poster', prompt: '/imagine prompt: Music festival poster, bold typography, neon energy, high contrast, lineup display, Electric Daisy Carnival style, poster print quality --ar 2:3 --stylize 750 --v 6', useCase: 'Event Marketing' },
    { id: 'art-long-18', title: 'Texture Pattern', prompt: '/imagine prompt: Seamless Moroccan tile pattern, geometric, gold on navy, elegant, luxury brand aesthetic, vector quality, repeating --ar 1:1 --stylize 250 --v 6', useCase: 'Design Resource' },
    { id: 'art-long-19', title: 'Icon Set Design', prompt: '/imagine prompt: Social media icon set, consistent minimalist style, uniform design language, works small, iOS quality --ar 1:1 --stylize 250 --v 6', useCase: 'App Design' },
    { id: 'art-long-20', title: 'Book Interior Illustration', prompt: '/imagine prompt: Chapter heading illustration, ornamental, classic book aesthetic, vintage typography space, elegant, detailed --ar 2:3 --stylize 500 --v 6', useCase: 'Book Design' }
  ],
  faqs: [
    { question: 'Which AI generator works best for these prompts?', answer: 'All prompts work with Midjourney V6 for best results. For DALL-E 3, remove artist references. Stable Diffusion works but needs adjustment.' },
    { question: 'Can I use these images commercially?', answer: 'With a paid subscription, you generally own images created. Check each platform\'s terms. Paid plans typically allow commercial use.' },
    { question: 'How do I get consistent results?', answer: 'Use the same aspect ratio and stylize value. Add --seed for reproducibility. Reference artists consistently for style matching.' },
    { question: 'What do the --ar and --stylize parameters mean?', answer: '--ar sets aspect ratio (16:9 cinematic, 1:1 square). --stylize controls artistic interpretation (250 strict, 750 default, 1000 experimental).' },
    { question: 'Why do some prompts give unexpected results?', answer: 'Very long prompts confuse the model. Keep focused on 2-3 key elements. Remove conflicting instructions. Use artist references carefully.' },
    { question: 'Can I mix elements from different prompts?', answer: 'Yes! Combine elements creatively. "steampunk airship in neon cyberpunk city" creates unique hybrid images.' },
    { question: 'How do I upscale images for print?', answer: 'Use Midjourney\'s upscale buttons (U1-U4) or an AI upscaler like Topaz Gigapixel for print-quality enlarge.' },
    { question: 'What parameters should I always include?', answer: '--v 6 for Midjourney. --ar for aspect ratio. --stylize 250-750 for commercial work. Optional: --seed for consistency.' }
  ],
  platformTips: [
    'Use --v 6 for best 2026 results in Midjourney',
    'Add --ar before generating: 16:9 cinematic, 1:1 Instagram, 9:16 social',
    'Use --stylize 250 for strict prompt following',
    'Reference artists like Greg Rutkowski for specific styles',
    'Add --seed for reproducible results',
    'Use --no to remove unwanted elements',
    'Keep prompts under 100 words for best results',
    'Combine prompts for unique hybrid images'
  ]
};