import { PromptPost } from './types';

export const chatgptScriptSummary: PromptPost = {
  slug: 'chatgpt-script-summary',
  title: 'ChatGPT Script Summary: Save Hours with This Prompt (2026)',
  keyword: 'chatgpt script summary',
  description: 'Save hours with this ChatGPT script summary prompt. Get quick summaries of long content.',
  date: '2026-04-21',
  category: 'Productivity',
  image: '/images/chatgpt-script-summary.jpg',
  content: `<p>Use this <strong>script summary prompt</strong> to quickly summarize any long content: articles, papers, docs, emails, and more.</p>`,
  shortPrompts: [
    { id: 'cs-1', prompt: 'Summarize this text in 3 bullet points. Each bullet 1 sentence. Include key actions needed.', description: 'Quick 3-bullet' },
    { id: 'cs-2', prompt: 'Extract the main idea, supporting points (3), and conclusion. No more than 100 words.', description: 'Main idea' },
    { id: 'cs-3', prompt: 'Turn this into a single tweet (280 chars). Include main point and CTA if any.', description: 'Tweet summary' },
    { id: 'cs-4', prompt: 'Create a TL;DR version. 1 paragraph, 3 sentences max.', description: 'TL;DR' },
    { id: 'cs-5', prompt: 'Extract all numbers/percentages with what they refer to.', description: 'Key numbers' },
    { id: 'cs-6', prompt: 'List action items. Who does what and by when?', description: 'Action items' },
    { id: 'cs-7', prompt: 'What are the key questions this answers? List them.', description: 'Questions' },
    { id: 'cs-8', prompt: 'What statistics appear? List each with context.', description: 'Stats' },
    { id: 'cs-9', prompt: 'Summarize the problem described. 2 sentences.', description: 'Problem' },
    { id: 'cs-10', prompt: 'What is the proposed solution? Summarize.', description: 'Solution' },
    { id: 'cs-11', prompt: 'Extract all mentions of costs/pricing.', description: 'Costs' },
    { id: 'cs-12', prompt: 'Who is mentioned and what is their role?', description: 'People' },
    { id: 'cs-13', prompt: 'Summarize the timeline given. List milestones.', description: 'Timeline' },
    { id: 'cs-14', prompt: 'What decisions need to be made?', description: 'Decisions' },
    { id: 'cs-15', prompt: 'What are the risks mentioned?', description: 'Risks' },
    { id: 'cs-16', prompt: 'Summarize benefits for [specific audience].', description: 'Benefits' },
    { id: 'cs-17', prompt: 'What terminology should I know? Define each.', description: 'Terms' },
    { id: 'cs-18', prompt: 'What tools/technologies are mentioned?', description: 'Tools' },
    { id: 'cs-19', prompt: 'What are alternatives mentioned and pros/cons?', description: 'Alternatives' },
    { id: 'cs-20', prompt: 'Convert to email subject line options - 3 variants.', description: 'Subject lines' },
    { id: 'cs-21', prompt: 'What should I do before reading more? Prerequisites.', description: 'Prerequisites' },
    { id: 'cs-22', prompt: 'What happens if I don\'t act? Consequences.', description: 'Consequences' },
    { id: 'cs-23', prompt: 'Who should read this? Target audience.', description: 'Audience' },
    { id: 'cs-24', prompt: 'What happens next? Next steps.', description: 'Next steps' },
    { id: 'cs-25', prompt: 'Create a 5-word summary and a 50-word summary.', description: 'Two summaries' }
  ],
  longPrompts: [
    { id: 'cs-long-1', title: 'Full Executive Summary', prompt: 'Create full executive summary: Background (2 sentences), Problem (2), Solution (3), Results expected (2), Investment needed (1), Call to action (1). Maximum 200 words total.', useCase: 'Executive Summary' },
    { id: 'cs-long-2', title: 'Meeting Notes', prompt: 'Turn into professional meeting notes: Attendees, agenda, discussion points (4+), decisions made, action items (who/when), next meeting date. Structured format.', useCase: 'Meeting Notes' },
    { id: 'cs-long-3', title: 'Article Analysis', prompt: 'Turn into article analysis: Main thesis, evidence used (3 types), strongest argument, weakest argument, author credibility assessment, key takeaway for reader.', useCase: 'Article Analysis' },
    { id: 'cs-long-4', title: 'Competitive Brief', prompt: 'Turn into competitive brief: Competitor name, key offering, strengths, weaknesses, threat level, our response recommendation. Include decision framework.', useCase: 'Competition' },
    { id: 'cs-long-5', title: 'Course Summary', prompt: 'Turn into course summary: Learning objectives (5), key modules (list), prerequisites, time needed, who would benefit most, enrollment recommendation.', useCase: 'Course' },
    { id: 'cs-long-6', title: 'Podcast Notes', prompt: 'Create podcast notes: Main topic, guest, key insights (5+), memorable quotes (2), episode rating (1-5) with why.', useCase: 'Podcast' },
    { id: 'cs-long-7', title: 'Process Documentation', prompt: 'Turn into process doc: Goal, steps (numbered), tools needed, common mistakes to avoid, quality checks. Actionable format.', useCase: 'Process' },
    { id: 'cs-long-8', title: 'Report Summary', prompt: 'Convert to report summary: Executive overview, methodology, key findings (3), implications, recommendations, data sources. Professional format.', useCase: 'Report' },
    { id: 'cs-long-9', title: 'Policy Brief', prompt: 'Create policy brief: Current policy, what changes, who benefits, implementation steps, potential opposition, approval likelihood. Decision-ready.', useCase: 'Policy' },
    { id: 'cs-long-10', title: 'Product Review', prompt: 'Create product review: Overview, pros (5), cons (3), alternatives, best for, worst for, rating (1-10) with justification. Comparison-focused.', useCase: 'Product' },
    { id: 'cs-long-11', title: 'Investment Summary', prompt: 'Create investment brief: Asset, current price, key metrics, bull case (3), bear case (3), recommendation (Buy/Hold/Sell) with rationale.', useCase: 'Investment' },
    { id: 'cs-long-12', title: 'Customer Feedback', prompt: 'Turn into feedback summary: Issue, frequency, impact, affected users, workaround, root cause likelihood, fix priority, recommended next steps.', useCase: 'Feedback' },
    { id: 'cs-long-13', title: 'Sales Pitch', prompt: 'Create sales pitch: Problem faced by customer, our solution, 3 key benefits, proof points, price range, CTA. Persuasive but accurate.', useCase: 'Sales' },
    { id: 'cs-long-14', title: 'SEO Content Brief', prompt: 'Create content brief: Target keyword, search intent, content type recommendation, word count target, subtopics to cover (5+), structure recommendation, internal linking ideas.', useCase: 'Content' },
    { id: 'cs-long-15', title: 'Legal Summary', prompt: 'Simplify for non-lawyer: What it says (plain English), key obligations, deadlines, what happens if violated, whether to sign. Clear language.', useCase: 'Legal' },
    { id: 'cs-long-16', title: 'Bug Report', prompt: 'Create bug report: Issue, reproduction steps, frequency, impact level, affected users, workaround, priority, recommended fix timeline.', useCase: 'Bugs' },
    { id: 'cs-long-17', title: 'Feature Request', prompt: 'Turn into feature request: Feature name, problem solved, user benefit, implementation complexity (1-5), priority recommendation, expected impact.', useCase: 'Features' },
    { id: 'cs-long-18', title: 'Email Triage', prompt: 'Categorize: Urgent/Not Urgent, Requires Response/For Info, Deadline (if any), 1-line action needed.', useCase: 'Email' },
    { id: 'cs-long-19', title: 'Book Chapter', prompt: 'Turn into chapter summary: Main argument, key examples (2), evidence, how it connects to overall book, key takeaway for reader.', useCase: 'Book' },
    { id: 'cs-long-20', title: 'YouTube Description', prompt: 'Create YouTube description: Hook (1-2 sentences), timestamps, key topics with timestamps, link in description, call to action. SEO-optimized.', useCase: 'YouTube' }
  ],
  faqs: [
    { question: 'Does this really save time?', answer: 'Yes! Summarizing takes minutes vs hours reading. Use saved time for action on insights.' },
    { question: 'What if I need more detail?', answer: 'After summary, ask Tell me more about specific point for targeted detail.' },
    { question: 'Can I summarize multiple items at once?', answer: 'Yes. Paste multiple and ask to summarize all of these. Works well.' },
    { question: 'What about confidential info?', answer: 'Use with caution for sensitive data. Review output vs original for accuracy.' },
    { question: 'Why output sometimes wrong?', answer: 'AI may miss nuance. Always verify important details. Use as starting point.' },
    { question: 'Can I use this for legal docs?', answer: 'Summary only, not for legal advice. Review key docs yourself.' },
    { question: 'How do I make summaries more accurate?', answer: 'Provide context in prompt: in 3 sentences or include costs.' },
    { question: 'Can I feed it multiple pages?', answer: 'Yes, but limit to key sections. Too much loses focus.' }
  ],
  platformTips: [
    'Paste less, summarize more - don\'t paste everything',
    'Be specific about output format needed',
    'Use follow-up for targeted details',
    'Try different summary styles',
    'Iterate until you get what you need',
    'Save prompts that work well',
    'Set context: "for CEO" or "for team"',
    'Use output as draft, review for accuracy'
  ]
};