import { PromptPost } from './types';

export const chatgptPPTPreset: PromptPost = {
  slug: 'chatgpt-ppt-preset',
  title: 'ChatGPT PPT Preset: Create Presentations 10x Faster (2026)',
  keyword: 'chatgpt ppt preset',
  description: 'Save hours with these ChatGPT prompts for creating PowerPoint presentations. Generate slides, outlines, and talking points instantly.',
  date: '2026-04-21',
  category: 'Productivity',
  image: '/images/chatgpt-ppt-preset.jpg',
  content: `<p>Use these <strong>ChatGPT presentation prompts</strong> to create professional slides in minutes instead of hours.</p>`,
  shortPrompts: [
    { id: 'ppt-1', prompt: 'Create a 10-slide outline for [TOPIC] presentation. Include: title, agenda, 3 main points, Conclusion, Q&A.', description: 'Basic outline' },
    { id: 'ppt-2', prompt: 'Write 5 bullet points for slide 1: [TOPIC]. Each bullet: 7 words max. Action-oriented.', description: 'Slide bullets' },
    { id: 'ppt-3', prompt: 'Write an opening hook for [TOPIC] presentation. 2 sentences. Compelling statistic + question.', description: 'Opening hook' },
    { id: 'ppt-4', prompt: 'Create 3 talking points for [CONCEPT]. Each 15 words. Include one example per point.', description: 'Talking points' },
    { id: 'ppt-5', prompt: 'Write 5 reasons why [TOPIC] matters. Each reason 1 sentence. Start with strong verb.', description: 'Key reasons' },
    { id: 'ppt-6', prompt: 'Create title slide text for [TOPIC]. Main title + subtitle. Professional, memorable.', description: 'Title slide' },
    { id: 'ppt-7', prompt: 'Write speaker notes for slide about [TOPIC]. 3 bullet points. Natural language for presenting.', description: 'Speaker notes' },
    { id: 'ppt-8', prompt: 'Create an analogy to explain [COMPLEX CONCEPT] to a 5-year-old. Simple, memorable.', description: 'Simple analogy' },
    { id: 'ppt-9', prompt: 'Write a conclusion summary for [TOPIC]. 4 key takeaways. Call to action included.', description: 'Conclusion' },
    { id: 'ppt-10', prompt: 'Create 5 potential Q&A for [TOPIC] presentation. Short answer for each.', description: 'Q&A prep' },
    { id: 'ppt-11', prompt: 'Write transition sentence from section 1 to section 2. Smooth, logical flow.', description: 'Transitions' },
    { id: 'ppt-12', prompt: 'Create agenda/outline slide for 30-minute [TOPIC] presentation. Time stamps included.', description: 'Timed agenda' },
    { id: 'ppt-13', prompt: 'Write closing statement for [TOPIC]. Memorable, inspiring. 2 sentences maximum.', description: 'Closing' },
    { id: 'ppt-14', prompt: 'Create data visualization ideas for [STAT]. 3 chart types that would work.', description: 'Data viz ideas' },
    { id: 'ppt-15', prompt: 'Write story opening for [TOPIC]. Personal or case study. Relatable hook.', description: 'Story hook' },
    { id: 'ppt-16', prompt: 'Create 4 section headers for [TOPIC] presentation. Engaging, descriptive.', description: 'Section headers' },
    { id: 'ppt-17', prompt: 'Write key insight/summary box text for slide [X]. 3 impactful points.', description: 'Insight box' },
    { id: 'ppt-18', prompt: 'Create "next steps" slide for [TOPIC]. 3-4 actionable items for audience.', description: 'Next steps' },
    { id: 'ppt-19', prompt: 'Write bio for speaker. Professional but personable. 2-3 sentences.', description: 'Speaker bio' },
    { id: 'ppt-20', prompt: 'Create comparison table content for [TOPIC] between Approach A vs B. 5 rows.', description: 'Comparison' },
    { id: 'ppt-21', prompt: 'Write problem statement for [TOPIC]. Clear, concise. Statistics supported.', description: 'Problem statement' },
    { id: 'ppt-22', prompt: 'Create impact numbers for [INITIATIVE]. Show before/after with metrics.', description: 'Impact metrics' },
    { id: 'ppt-23', prompt: 'Write team member introductions for [TOPIC]. Name, role, one unique detail.', description: 'Team intro' },
    { id: 'ppt-24', prompt: 'Create timeline graphic text for [PROJECT]. 4-5 milestones with dates.', description: 'Timeline' },
    { id: 'ppt-25', prompt: 'Write thank you + contact slide. Professional sign-off with multiple contact options.', description: 'Thank you' }
  ],
  longPrompts: [
    { id: 'ppt-long-1', title: 'Full Presentation Outline', prompt: 'Create complete 20-slide presentation on [TOPIC]: title, agenda, 5 sections with 3 slides each, conclusion, Q&A. Include presenter notes. Professional business format.', useCase: 'Full Deck' },
    { id: 'ppt-long-2', title: 'Investor Pitch Structure', prompt: 'Create investor pitch deck: problem (2 slides), solution (3 slides), market (2 slides), business model (2 slides), team (1 slide), ask (1 slide). Compelling, data-backed.', useCase: 'Investor Pitch' },
    { id: 'ppt-long-3', title: 'Training Workshop', prompt: 'Create 45-minute training on [SKILL]: objectives, setup, 5 activities (15 min each), materials list, assessment questions. Hands-on format.', useCase: 'Training' },
    { id: 'ppt-long-4', title: 'Product Launch', prompt: 'Create product launch deck: teaser, problem, solution, product intro, features (4), pricing, timeline, team, Q&A. Exciting, sales-focused.', useCase: 'Product Launch' },
    { id: 'ppt-long-5', title: 'Monthly Report Template', prompt: 'Create monthly status report: executive summary, key metrics (3), wins (3), challenges (2), next month priorities (4), resource needs. Clear, data-driven.', useCase: 'Monthly Report' },
    { id: 'ppt-long-6', title: 'Strategy Presentation', prompt: 'Create strategic planning deck: current state, vision, 3 strategic pillars, initiatives per pillar (3), timeline, resource requirements, success metrics. Executive format.', useCase: 'Strategy' },
    { id: 'ppt-long-7', title: 'Educational Lecture', prompt: 'Create 60-minute lecture on [CONCEPT]: learning objectives, 5 key topics, 2-3 examples each, discussion questions, key takeaways, homework. Academic format.', useCase: 'Lecture' },
    { id: 'ppt-long-8', title: 'Case Study Deep Dive', prompt: 'Create case study presentation: client challenge, approach, implementation, results (with metrics), lessons learned. Storytelling format.', useCase: 'Case Study' },
    { id: 'ppt-long-9', title: 'Quarterly Review', prompt: 'Create QBR deck: quarterly highlights, metric dashboard, team wins, challenges, learnings, next quarter priorities, resource ask. Results-focused.', useCase: 'Quarterly Review' },
    { id: 'ppt-long-10', title: 'Process Overview', prompt: 'Create process training: process overview, step-by-step (8 steps), common mistakes, best practices, troubleshooting, resources. Clear visual flow.', useCase: 'Process Training' },
    { id: 'ppt-long-11', title: 'Company All-Hands', prompt: 'Create all-hands update: CEO message, company metrics, team spotlights (3), upcoming priorities, Q&A prep. Culture-focused, inspiring.', useCase: 'All-Hands' },
    { id: 'ppt-long-12', title: 'Sales Demo Script', prompt: 'Create demo script: problem statement, solution overview, live demo steps (5 scenarios), pricing reveal, competitor comparison, closing. Demo-driven.', useCase: 'Demo Script' },
    { id: 'ppt-long-13', title: 'Onboarding Deck', prompt: 'Create new hire onboarding: company mission, team structure, tools, processes, first week tasks, contacts, resources. Welcome-focused.', useCase: 'Onboarding' },
    { id: 'ppt-long-14', title: 'Crisis Communication', prompt: 'Create crisis response: situation overview, immediate actions, stakeholder communication, resolution steps, lessons learned. Calm, decisive.', useCase: 'Crisis Response' },
    { id: 'ppt-long-15', title: 'Annual Planning', prompt: 'Create annual planning deck: last year review, market analysis, goals (3), strategies, tactics, budget, timeline. Strategic format.', useCase: 'Annual Planning' },
    { id: 'ppt-long-16', title: 'Conference Talk', prompt: 'Create conference-ready talk: hook (2 min), 5 key insights with stories, key takeaway, call to action. TED-style structure.', useCase: 'Conference' },
    { id: 'ppt-long-17', title: 'Board Presentation', prompt: 'Create board update: executive summary, financial highlights, strategic progress, risks, decisions needed, ask. Concise, data-backed.', useCase: 'Board Update' },
    { id: 'ppt-long-18', title: 'Project Kickoff', prompt: 'Create project kickoff: project overview, objectives, timeline, roles, milestones, communication plan, risks. Alignment-focused.', useCase: 'Kickoff' },
    { id: 'ppt-long-19', title: 'Customer Success Deck', prompt: 'Create customer success framework: value delivered, success metrics, expansion opportunities, case study, next steps. Relationship-focused.', useCase: 'Customer Success' },
    { id: 'ppt-long-20', title: 'Leadership Update', prompt: 'Create leadership presentation: vision reinforcement, priorities, organizational changes, Q&A prep. Trust-building format.', useCase: 'Leadership Update' }
  ],
  faqs: [
    { question: 'How do I use these prompts effectively?', answer: 'Replace [TOPIC] with your actual subject. Add context like audience, time limit, or format for better results.' },
    { question: 'Can these create actual PowerPoint files?', answer: 'ChatGPT creates the content. Copy into PowerPoint or use AI plugins that generate slides directly.' },
    { question: 'How long does it take?', answer: '5-10 minutes for full outlines. 30-60 minutes to copy into actual slides.' },
    { question: 'Can I customize the output style?', answer: 'Add: "use simple words" or "executive professional" or "conversational tone" to prompts.' },
    { question: 'What about design?', answer: 'ChatGPT handles content. For design, use PowerPoint templates or design tools. Content first!' },
    { question: 'Can I combine prompts?', answer: 'Yes! Use outline prompt first, then bullet prompts for specific slides. Layer for depth.' },
    { question: 'What if output is too long?', answer: 'Add word/slide limits to prompts: "3 slides maximum" or "under 100 words".' },
    { question: 'How do I make it more engaging?', answer: 'Add: "include stories" or "add statistics" or "use questions to engage audience".' }
  ],
  platformTips: [
    'Always replace placeholder like [TOPIC] with your specific subject',
    'Add audience type: "for executives" or "for beginners" for targeted output',
    'Specify length: "5 slides" or "300 words" for right sizing',
    'Include timezone context for demos or time-specific content',
    'Ask for speaker notes separately for detailed presenting',
    'Request "one idea per slide" for focused content',
    'Use "markdown format" for easy copy-paste into slides',
    'Iterate: use output as foundation, refine in follow-up prompts'
  ]
};