import { PromptPost } from './types';

export const drawingPromptGenerator: PromptPost = {
  slug: 'drawing-prompt-generator',
  title: 'Drawing Prompt Generator: 50+ Creative Ideas (2026)',
  keyword: 'drawing prompt generator',
  description: 'Generate creative drawing ideas with our prompt generator. 50+ prompts for sketches, illustrations, and artwork.',
  date: '2026-04-21',
  category: 'Art',
  image: '/images/drawing-prompt-generator.jpg',
  content: `<p>Use these creative <strong>drawing prompt generator</strong> ideas to spark your next masterpiece.</p>`,
  shortPrompts: [
    { id: 'drawgen-1', prompt: 'Draw a magical key that opens any door', description: 'Fantasy object' },
    { id: 'drawgen-2', prompt: 'Draw a clock with no hands', description: 'Surreal concept' },
    { id: 'drawgen-3', prompt: 'Draw your spirit animal', description: 'Personal symbol' },
    { id: 'drawgen-4', prompt: 'Draw a room from your childhood home', description: 'Memory scene' },
    { id: 'drawgen-5', prompt: 'Draw an old map of somewhere that doesn\'t exist', description: 'Map creation' },
    { id: 'drawgen-6', prompt: 'Draw a creature from your dreams', description: 'Dream creature' },
    { id: 'drawgen-7', prompt: 'Draw what your name looks like as a symbol', description: 'Personal logo' },
    { id: 'drawgen-8', prompt: 'Draw a tree with meaningful objects hanging from branches', description: 'Symbolic tree' },
    { id: 'drawgen-9', prompt: 'Draw your favorite place on earth from photo reference', description: 'Beloved place' },
    { id: 'drawgen-10', prompt: 'Draw a superhero based on your personality', description: 'Original hero' },
    { id: 'drawgen-11', prompt: 'Draw an object that represents your current emotion', description: 'Emotional art' },
    { id: 'drawgen-12', prompt: 'Draw a vehicle from the future', description: 'Futuristic transport' },
    { id: 'drawgen-13', prompt: 'Draw a portrait of someone you admire', description: 'Tribute portrait' },
    { id: 'drawgen-14', prompt: 'Draw the view from your window', description: 'From memory' },
    { id: 'drawgen-15', prompt: 'Draw a pattern inspired by nature', description: 'Nature pattern' },
    { id: 'drawgen-16', prompt: 'Draw a book cover for your autobiography', description: 'Self-portrait' },
    { id: 'drawgen-17', prompt: 'Draw a still life with sentimental items', description: 'Personal still life' },
    { id: 'drawgen-18', prompt: 'Draw a costume for an imaginary holiday', description: 'Creative costume' },
    { id: 'drawgen-19', prompt: 'Draw an animal that doesn\'t exist', description: 'Imaginary creature' },
    { id: 'drawgen-20', prompt: 'Draw the same hand in 5 different poses', description: 'Hand study' },
    { id: 'drawgen-21', prompt: 'Draw your happy place', description: 'Peaceful scene' },
    { id: 'drawgen-22', prompt: 'Draw a logo for a fictional company', description: 'Brand design' },
    { id: 'drawgen-23', prompt: 'Draw a scene from your favorite book', description: 'Literary art' },
    { id: 'drawgen-24', prompt: 'Draw something broken beautifully', description: 'Artistic destruction' },
    { id: 'drawgen-25', prompt: 'Draw your ideal home', description: 'Dream space' }
  ],
  longPrompts: [
    { id: 'drawgen-long-21', title: 'Fantasy Character Design', prompt: 'Design a complete fantasy character: face, costume, weapons, and accessories. Show their story through details.', useCase: 'Character Design' },
    { id: 'drawgen-long-2', title: 'City Street Scene', prompt: 'Draw a busy city street with multiple floors, people, vehicles, and signs. Show energy and life.', useCase: 'Urban Scene' },
    { id: 'drawgen-long-3', title: 'Detailed Botanical Study', prompt: 'Draw a flower or plant with scientific accuracy: all petals, leaves, stem, showing both macro and botanical details.', useCase: 'Botanical Art' },
    { id: 'drawgen-long-4', title: 'Interior Design', prompt: 'Design a room interior: furniture, lighting, decor, personal touches. Show personality through possessions.', useCase: 'Interior Illustration' },
    { id: 'drawgen-long-5', title: 'Creature Mashup', prompt: 'Combine 3 different animals into one creature. Make it anatomically believable and show its habitat.', useCase: 'Creature Design' },
    { id: 'drawgen-long-6', title: 'Historical Fashion', prompt: 'Research and draw someone in traditional clothing from a different culture or time period. Be respectful and accurate.', useCase: 'Historical Fashion' },
    { id: 'drawgen-long-7', title: 'Emotion Visualization', prompt: 'Draw an abstract representation of an emotion: anger, joy, sadness, love. Use color, shape, and movement.', useCase: 'Abstract Art' },
    { id: 'drawgen-long-8', title: 'Sci-Fi Environment', prompt: 'Draw an alien environment: strange plants, unusual sky, unique features. Build a complete ecosystem.', useCase: 'World Building' },
    { id: 'drawgen-long-9', title: 'Architectural Detail', prompt: 'Draw detailed architecture: a building façade or interior with architectural precision. Include materials.', useCase: 'Architectural Art' },
    { id: 'drawgen-long-10', title: 'Food Illustration', prompt: 'Draw a complete meal with multiple dishes, arranged beautifully. Show style and presentation.', useCase: 'Food Art' },
    { id: 'drawgen-long-11', title: 'Mythological Scene', prompt: 'Illustrate a scene from mythology: Greek, Norse, Egyptian, or another tradition. Research first.', useCase: 'Mythology' },
    { id: 'drawgen-long-12', title: 'Animal Portrait', prompt: 'Draw an animal portrait with emotional depth. Capture personality in their eyes and posture.', useCase: 'Animal Art' },
    { id: 'drawgen-long-13', title: 'Fashion Illustration', prompt: 'Draw a fashion figure in contemporary clothing. Focus on fabric, drape, and movement.', useCase: 'Fashion Design' },
    { id: 'drawgen-long-14', title: 'Mechanical Design', prompt: 'Design a machine or device: functional, detailed, with moving parts and logical mechanisms.', useCase: 'Mechanical Art' },
    { id: 'drawgen-long-15', title: 'Seasonal Series', prompt: 'Create a 4-panel series showing the same scene in spring, summer, autumn, and winter. Show change.', useCase: 'Sequential Art' },
    { id: 'drawgen-long-16', title: 'Book Scene', prompt: 'Illustrate a scene from any book. Capture the key moment and atmosphere from the story.', useCase: 'Literary Illustration' },
    { id: 'drawgen-long-17', title: 'Vehicle Design', prompt: 'Design a complete vehicle: car, plane, boat. Show all angles and interior details.', useCase: 'Vehicle Design' },
    { id: 'drawgen-long-18', title: 'Family Portrait', prompt: 'Draw a stylized family portrait: yours, fictional, or mixed. Show relationships through composition.', useCase: 'Portrait Art' },
    { id: 'drawgen-long-19', title: 'Abstract Composition', prompt: 'Create an abstract piece using only shapes and colors. No recognizable subject - pure composition.', useCase: 'Abstract Art' },
    { id: 'drawgen-long-20', title: 'Story Sequence', prompt: 'Tell a complete story in 3-4 sequential images. Show beginning, middle, end with clear narrative.', useCase: 'Comic Art' }
  ],
  faqs: [
    { question: 'How do I choose the right prompt?', answer: 'Pick what resonates emotionally. If nothing calls to you, close your eyes and point - go with your first instinct.' },
    { question: 'What materials work best for these prompts?', answer: 'Any! Pencil, pen, digital, watercolor. Use what you have. The prompt matters more than tools.' },
    { question: 'How long should I spend on each drawing?', answer: 'Quick prompts: 10-30 minutes. Long prompts: 1-3 hours. Neither is wrong - just draw.' },
    { question: 'What if my drawing doesn\'t look like what I imagined?', answer: 'This is learning! Every "failure" teaches you something about form, light, or composition.' },
    { question: 'Can I combine multiple prompts?', answer: 'Absolutely. Draw a magical key in your vehicle from the future for unique ideas.' },
    { question: 'Should I use reference photos?', answer: 'It depends. For memory prompts, draw from memory first. For new subjects, references help.' },
    { question: 'How do I develop my own style through prompts?', answer: 'Draw what genuinely interests you. Over time, your unique voice emerges.' },
    { question: 'What if I run out of ideas?', answer: 'That is when prompts help. Use random selection, flip a coin.' }
  ],
  platformTips: [
    'Keep a sketchbook handy for every prompt',
    'Set a timer and draw quickly - speed builds skill',
    'Don\'t erase - learn from "mistakes"',
    'Use reference for accuracy, then try from memory',
    'Share work online for feedback and motivation',
    'Draw the same prompt multiple times over months',
    'Try different mediums for variety',
    'Join drawing communities for challenges'
  ]
};