import { PromptPost } from './types';

export const drawingPrompts: PromptPost = {
  slug: 'drawing-prompts',
  title: 'Drawing Prompts: 50+ Creative Ideas to Spark Your Art (2026)',
  keyword: 'drawing prompts',
  description: 'Get 50+ creative drawing prompts for all skill levels. From beginner to advanced - spark your creativity with these unique art ideas.',
  date: '2026-04-21',
  category: 'Art',
  image: '/images/drawing-prompts.jpg',
  content: `<p>These <strong>drawing prompts</strong> will help you overcome artist block and discover new creative directions.</p>`,
  shortPrompts: [
    { id: 'draw-1', prompt: 'Draw a cozy coffee shop window view', description: 'Cozy café scene' },
    { id: 'draw-2', prompt: 'Draw your childhood home from memory', description: 'Memory sketch' },
    { id: 'draw-3', prompt: 'Draw a pair of worn hiking boots', description: 'Still life' },
    { id: 'draw-4', prompt: 'Draw your favorite food from childhood', description: 'Nostalgic food' },
    { id: 'draw-5', prompt: 'Draw a treehouse in autumn', description: 'Fantasy landscape' },
    { id: 'draw-6', prompt: 'Draw a cat sleeping in a sunbeam', description: 'Peaceful scene' },
    { id: 'draw-7', prompt: 'Draw an old book with wax seal', description: 'Vintage still life' },
    { id: 'draw-8', prompt: 'Draw a superhero from your imagination', description: 'Character design' },
    { id: 'draw-9', prompt: 'Draw a rainy city street at night', description: 'Urban mood' },
    { id: 'draw-10', prompt: 'Draw a garden shed full of tools', description: 'Detailed scene' },
    { id: 'draw-11', prompt: 'Draw your pet or a pet you wish you had', description: 'Animal portrait' },
    { id: 'draw-12', prompt: 'Draw a lighthouse in a storm', description: 'Dramatic scene' },
    { id: 'draw-13', prompt: 'Draw a musician performing on stage', description: 'Action scene' },
    { id: 'draw-14', prompt: 'Draw an abandoned factory', description: 'Industrial landscape' },
    { id: 'draw-15', prompt: 'Draw a plate of sushi', description: 'Food art' },
    { id: 'draw-16', prompt: 'Draw a dragon curled around a castle', description: 'Fantasy creature' },
    { id: 'draw-17', prompt: 'Draw your morning routine items', description: 'Daily still life' },
    { id: 'draw-18', prompt: 'Draw a fantasy map of an imaginary land', description: 'Map making' },
    { id: 'draw-19', prompt: 'Draw a crowded farmers market', description: 'Busy scene' },
    { id: 'draw-20', prompt: 'Draw a celestial map with constellations', description: 'Astronomical art' },
    { id: 'draw-21', prompt: 'Draw an old photograph of your grandparents', description: 'Portrait tribute' },
    { id: 'draw-22', prompt: 'Draw a secret garden with hidden paths', description: 'Fantasy garden' },
    { id: 'draw-23', prompt: 'Draw your favorite movie scene', description: 'Fan art' },
    { id: 'draw-24', prompt: 'Draw a vintage bicycle', description: 'Classic object' },
    { id: 'draw-25', prompt: 'Draw a fantasy weapon of your design', description: 'Weapon design' }
  ],
  longPrompts: [
    { id: 'draw-long-1', title: 'Building A Cityscape', prompt: 'Design a futuristic city with flying cars, holographic signs, and massive glass towers. Show both wealthy and working-class sections.', useCase: 'Concept Art' },
    { id: 'draw-long-2', title: 'Character: The Wise Elder', prompt: 'Create a portrait of a wise elder with deep lines, kind eyes, wearing traditional robes from any culture you choose.', useCase: 'Portrait Practice' },
    { id: 'draw-long-3', title: 'Underwater Scene', prompt: 'Draw a coral reef scene with tropical fish, a diver exploring, and light rays streaming from above.', useCase: 'Nature Illustration' },
    { id: 'draw-long-4', title: 'Fairytale Cottage', prompt: 'Design a whimsical cottage in the woods with smoke rising, mushrooms nearby, and fairy lights.', useCase: 'Fantasy Art' },
    { id: 'draw-long-5', title: 'Mechanical Creature', prompt: 'Invent a creature that is part organic, part machine. Show it in its natural environment.', useCase: 'Sci-Fi Design' },
    { id: 'draw-long-6', title: 'Street Market Bustle', prompt: 'Capture the energy of a busy street market with vendors, customers, and goods displayed everywhere.', useCase: 'Urban Sketching' },
    { id: 'draw-long-7', title: 'Ancient Temple', prompt: 'Design an ancient temple hidden in the jungle, with vines and moss covering weathered stones.', useCase: 'Architectural Design' },
    { id: 'draw-long-8', title: 'Portrait in Multiple Styles', prompt: 'Draw the same face in 4 different art styles: realistic, cartoon, abstract, and cubist.', useCase: 'Style Practice' },
    { id: 'draw-long-9', title: 'Space Station Living Quarters', prompt: 'Design the interior of a space station room showing personal items, views of Earth, and zero-g的生活.', useCase: 'Sci-Fi Interior' },
    { id: 'draw-long-10', title: 'Seasonal Changes', prompt: 'Draw the same tree in all four seasons, showing how changing foliage transforms the scene.', useCase: 'Nature Series' },
    { id: 'draw-long-11', title: 'Folklore Creature', prompt: 'Research and draw a creature from your culture folklore, showing its environment and story.', useCase: 'Cultural Art' },
    { id: 'draw-long-12', title: 'Musical Instrument Close-up', prompt: 'Draw an old, well-loved musical instrument with wear marks, repairs, and character.', useCase: 'Detail Study' },
    { id: 'draw-long-13', title: 'Dreamscape', prompt: 'Illustrate a dream-like scene where impossible things happen - gravity doesn\'t work, colors blend.', useCase: 'Surreal Art' },
    { id: 'draw-long-14', title: 'Historical Moment', prompt: 'Research and draw a moment from history that interests you, showing the scene accurately.', useCase: 'Historical Art' },
    { id: 'draw-long-15', title: 'Inner World', prompt: 'Illustrate what someone\'s "inner world" might look like - their hopes, fears, and dreams visualized.', useCase: 'Conceptual Art' },
    { id: 'draw-long-16', title: 'Wild West Scene', prompt: 'Design a classic Western scene: dusty town, cowboy on horseback, dramatic sunset.', useCase: 'Western Art' },
    { id: 'draw-long-17', title: 'Tea Ceremony', prompt: 'Draw a traditional tea ceremony scene with all necessary items and atmosphere.', useCase: 'Cultural Scene' },
    { id: 'draw-long-18', title: 'Alien Ecosystem', prompt: 'Create an entire ecosystem on a fictional alien planet with unique plants and creatures.', useCase: 'World Building' },
    { id: 'draw-long-19', title: 'The Same Room, Different Moods', prompt: 'Draw the same room: first cheerful morning light, then cozy evening, then mysterious at night.', useCase: 'Lighting Study' },
    { id: 'draw-long-20', title: 'Mythological Gathering', prompt: 'Draw a gathering of mythological beings from different cultures sharing a meal together.', useCase: 'Fantasy Characters' }
  ],
  faqs: [
    { question: 'How do I start when I have no inspiration?', answer: 'Start with simple objects around you. Draw your coffee cup, a shoe, your hand. Daily objects can become interesting when you really look at them.' },
    { question: 'Should I draw from photos or real life?', answer: 'Both! Real life helps you understand depth and light. Photos are convenient and let you capture moments you can\'t sit for. Use both for best growth.' },
    { question: 'How can I develop my own style?', answer: 'Style develops naturally through consistent practice. Don\'t try to force it. Draw what genuinely interests you, and your unique voice will emerge.' },
    { question: 'What if my drawings don\'t look like I imagined?', answer: 'This is normal! The gap between vision and execution is where growth happens. Every drawing teaches you something, even "failures."' },
    { question: 'How often should I practice drawing?', answer: 'Consistency matters more than duration. 30 minutes daily beats 4 hours once a week. Keep a sketchbook handy for quick warm-ups.' },
    { question: 'Should I learn fundamentals before creative prompts?', answer: 'Fundamentals and creative prompts actually work together. Learning basics helps you execute ideas, while prompts keep practice fun and meaningful.' },
    { question: 'How do I get better at drawing people?', answer: 'Practice gesture drawing - quick sketches that capture pose and movement. Study anatomy slowly. Draw people in public places (cafes, parks) when you can.' },
    { question: 'What materials should I use?', answer: 'Start simple: a sketchbook and pencils (2B, 4B, 6B). Once you have a habit, experiment with pens, ink, watercolor, or digital tools.' }
  ],
  platformTips: [
    'Keep a sketchbook with you for spontaneous drawing sessions',
    'Set a timer for quick gesture drawings to build speed',
    'Draw the same subject multiple times to see your improvement',
    'Study artists you admire and try to understand their techniques',
    'Don\'t erase - learn to love "mistakes" as happy accidents',
    'Draw from life as much as possible for better understanding',
    'Join online drawing communities for motivation and feedback',
    'Try drawing with your non-dominant hand to loosen up'
  ]
};