import { PromptPost } from './types';

export const gaugePrompts: PromptPost = {
  slug: 'gauge-prompts',
  title: 'Gauge Prompts: 50+ Measurement & Survey Questions (2026)',
  keyword: 'gauge prompts',
  description: 'Gauge prompts - 50+ questions for surveys, feedback, and measurement.',
  date: '2026-04-21',
  category: 'Research',
  image: '/images/gauge-prompts.jpg',
  content: `<p>Use these <strong>gauge prompts</strong> for surveys, feedback forms, and measurement tools.</p>`,
  shortPrompts: [
    { id: 'gp-1', prompt: 'How satisfied are you with our service? (1-10)', description: 'Satisfaction scale' },
    { id: 'gp-2', prompt: 'How likely are you to recommend us? (0-10)', description: 'NPS question' },
    { id: 'gp-3', prompt: 'How often do you use our product?', description: 'Usage frequency' },
    { id: 'gp-4', prompt: 'What is your primary goal?', description: 'Goal identification' },
    { id: 'gp-5', prompt: 'Rate your agreement: Strongly disagree to strongly agree', description: 'Agreement scale' },
    { id: 'gp-6', prompt: 'What feature is most important to you?', description: 'Feature priority' },
    { id: 'gp-7', prompt: 'How would you rate quality? (Poor to Excellent)', description: 'Quality rating' },
    { id: 'gp-8', prompt: 'What is your biggest challenge?', description: 'Challenge identification' },
    { id: 'gp-9', prompt: 'How did you find us?', description: 'Discovery source' },
    { id: 'gp-10', prompt: 'Would you use us again? (Yes/No)', description: 'Repeat usage' },
    { id: 'gp-11', prompt: 'What is your budget range?', description: 'Budget gauge' },
    { id: 'gp-12', prompt: 'How urgent is your need?', description: 'Urgency level' },
    { id: 'gp-13', prompt: 'Rate your experience: 1 star to 5 stars', description: 'Star rating' },
    { id: 'gp-14', prompt: 'What stopped you from purchasing?', description: 'Barriers' },
    { id: 'gp-15', prompt: 'What would improve your experience?', description: 'Improvement ideas' },
    { id: 'gp-16', prompt: 'How long have you been a customer?', description: 'Tenure' },
    { id: 'gp-17', prompt: 'Which best describes you?', description: 'Customer type' },
    { id: 'gp-18', prompt: 'How confident are you?', description: 'Confidence level' },
    { id: 'gp-19', prompt: 'What is your timeline?', description: 'Timeline' },
    { id: 'gp-20', prompt: 'Rate usability: Very difficult to Very easy', description: 'Usability' },
    { id: 'gp-21', prompt: 'Which option matches your preference?', description: 'Preference selection' },
    { id: 'gp-22', prompt: 'How aware were you of our brand?', description: 'Brand awareness' },
    { id: 'gp-23', prompt: 'How much time did you spend?', description: 'Time spent' },
    { id: 'gp-24', prompt: 'How would you describe your skill level?', description: 'Skill level' },
    { id: 'gp-25', prompt: 'What is your decision timeline?', description: 'Decision timeline' }
  ],
  longPrompts: [
    { id: 'gp-long-1', title: 'Customer Satisfaction Survey', prompt: 'Full CSAT survey: rate overall experience, rate specific aspects, open feedback section, would recommend, follow-up permission.', useCase: 'CSAT Survey' },
    { id: 'gp-long-2', title: 'Net Promoter Score', prompt: 'NPS survey: likelihood to recommend 0-10, reason for score, improvement ideas.', useCase: 'NPS Survey' },
    { id: 'gp-long-3', title: 'Product Feedback', prompt: 'Product feedback: what worked, what did not, missing features, likelihood to repurchase.', useCase: 'Product Feedback' },
    { id: 'gp-long-4', title: 'Event Evaluation', prompt: 'Event feedback: overall satisfaction, presenter quality, content relevance, venue, networking value.', useCase: 'Event Survey' },
    { id: 'gp-long-5', title: 'User Experience Survey', prompt: 'UX survey: ease of use, navigation clarity, page load speed, mobile experience, desired features.', useCase: 'UX Survey' },
    { id: 'gp-long-6', title: 'Employee Engagement', prompt: 'Engagement survey: job satisfaction, manager relationship, growth opportunities, work-life balance.', useCase: 'HR Survey' },
    { id: 'gp-long-7', title: 'Brand Perception', prompt: 'Brand survey: brand awareness, perception, uniqueness vs competitors, trust level.', useCase: 'Brand Survey' },
    { id: 'gp-long-8', title: 'Market Research', prompt: 'Market research: price sensitivity, feature priorities, competitive analysis, trends.', useCase: 'Market Research' },
    { id: 'gp-long-9', title: 'Lead Qualification', prompt: 'Lead qualification: budget authority need timeline, pain points, current solution.', useCase: 'Sales Qualification' },
    { id: 'gp-long-10', title: 'Website Feedback', prompt: 'Website feedback: design appeal, content usefulness, conversion ease, mobile experience.', useCase: 'Website Survey' },
    { id: 'gp-long-11', title: 'Training Evaluation', prompt: 'Training feedback: content relevance, delivery quality, practical application, facilitator.', useCase: 'Training Survey' },
    { id: 'gp-long-12', title: 'Customer Effort Score', prompt: 'CES: ease of solving problem, clarity of process, time required, support satisfaction.', useCase: 'CES Survey' },
    { id: 'gp-long-13', title: 'Product Market Fit', prompt: 'PMF survey: problem importance, solution quality, uniqueness, recommendation likelihood.', useCase: 'PMF Survey' },
    { id: 'gp-long-14', title: 'Support Satisfaction', prompt: 'Support survey: resolution satisfaction, response time, agent knowledge, follow-up quality.', useCase: 'Support Survey' },
    { id: 'gp-long-15', title: 'Subscription Renewal', prompt: 'Renewal likelihood, value perception, feature usage, competitor consideration, plans.', useCase: 'Renewal Survey' },
    { id: 'gp-long-16', title: 'Onboarding Feedback', prompt: 'Onboarding experience: ease of getting started, resource clarity, support access, time to first success.', useCase: 'Onboarding Survey' },
    { id: 'gp-long-17', title: 'Community Feedback', prompt: 'Community engagement: participation frequency, value received, content quality.', useCase: 'Community Survey' },
    { id: 'gp-long-18', title: 'Price Sensitivity', prompt: 'Price research: willingness to pay, price tiers, value perception, discount impact.', useCase: 'Price Research' },
    { id: 'gp-long-19', title: 'Content Satisfaction', prompt: 'Content survey: content helpfulness, format preference, topics wanted.', useCase: 'Content Survey' },
    { id: 'gp-long-20', title: 'Overall Health Check', prompt: 'Comprehensive metrics: NPS, CSAT, CES, usage, retention risk, growth potential.', useCase: 'Health Check' }
  ],
  faqs: [
    { question: 'How many questions should a survey have?', answer: 'Keep under 10 for best completion rates. More needs incentive.' },
    { question: 'What scales work best?', answer: '0-10 for NPS. 1-5 or 1-7 for Likert. 1-10 for satisfaction.' },
    { question: 'Should I use open-ended questions?', answer: 'Yes, but sparingly. They provide depth. Use at end for anything else.' },
    { question: 'How do I ensure honest answers?', answer: 'Anonymous increases honesty. Third-party feels safer.' },
    { question: 'When should I survey?', answer: 'Immediately post-experience for accuracy. At natural milestones.' },
    { question: 'What makes questions clear?', answer: 'One question at a time. Simple language. Avoid double negatives.' },
    { question: 'How do I increase response rates?', answer: 'Short surveys. Mobile-responsive. Incentives. Personalization.' },
    { question: 'How do I measure sentiment?', answer: 'Direct NPS question. Open ends for context.' }
  ],
  platformTips: [
    'Use consistent scales across survey',
    'Make scales balanced (odd numbers allow neutral)',
    'Anchor scale labels (Very Poor to Very Good)',
    'Randomize answer order to reduce bias',
    'Set clear expectations: time needed',
    'Test survey before sending broadly',
    'Follow-up on low scores quickly',
    'Track metrics over time for trends'
  ]
};