import { PromptPost } from './types';

export const googleWhiskGuide: PromptPost = {
  slug: 'google-whisk-guide',
  title: 'Google Whisk Image Prompt Guide: Create AI Images (2026)',
  keyword: 'google whisk prompt guide',
  description: 'Step-by-step guide to creating AI images with Google Whisk. Learn prompt engineering for best results.',
  date: '2026-04-21',
  category: 'Image Generation',
  image: '/images/google-whisk-guide.jpg',
  content: `<p>Master <strong>Google Whisk</strong> with this comprehensive guide to creating AI-generated images.</p>`,
  shortPrompts: [
    { id: 'whisk-1', prompt: 'Subject: golden retriever on beach at sunset, mood: happy, style: photorealistic', description: 'Beach dog' },
    { id: 'whisk-2', prompt: 'Subject: vintage motorcycle, mood: retro, style: film photography', description: 'Vintage bike' },
    { id: 'whisk-3', prompt: 'Subject: Tokyo street at night, mood: vibrant, style: cyberpunk', description: 'Tokyo night' },
    { id: 'whisk-4', prompt: 'Subject: mountain cabin in snow, mood: cozy, style: oil painting', description: 'Snow cabin' },
    { id: 'whisk-5', prompt: 'Subject: sushi plate, mood: appetizing, style: food photography', description: 'Sushi' },
    { id: 'whisk-6', prompt: 'Subject: old bookstore, mood: mysterious, style: dramatic', description: 'Old bookshop' },
    { id: 'whisk-7', prompt: 'Subject: sunflower field, mood: joyful, style: impressionist', description: 'Sunflowers' },
    { id: 'whisk-8', prompt: 'Subject: city skyline, mood: powerful, style: minimalist', description: 'Skyline' },
    { id: 'whisk-9', prompt: 'Subject: laptop workspace, mood: productive, style: flat lay', description: 'Workspace' },
    { id: 'whisk-10', prompt: 'Subject: autumn leaves, mood: nostalgic, style: macro photography', description: 'Autumn leaves' },
    { id: 'whisk-11', prompt: 'Subject: coral reef, mood: magical, style: underwater photography', description: 'Coral reef' },
    { id: 'whisk-12', prompt: 'Subject: street food stall, mood: lively, style: documentary', description: 'Street food' },
    { id: 'whisk-13', prompt: 'Subject: wild wolf, mood: noble, style: wildlife photography', description: 'Wild wolf' },
    { id: 'whisk-14', prompt: 'Subject: night sky stars, mood: peaceful, style: astrophotography', description: 'Stars' },
    { id: 'whisk-15', prompt: 'Subject: rustic kitchen, mood: warm, style: lifestyle photography', description: 'Rustic kitchen' },
    { id: 'whisk-16', prompt: 'Subject: street artist mural, mood: colorful, style: urban art', description: 'Street art' },
    { id: 'whisk-17', prompt: 'Subject: newborn baby, mood: innocent, style: portrait', description: 'Baby portrait' },
    { id: 'whisk-18', prompt: 'Subject: desert landscape, mood: vast, style: landscape', description: 'Desert' },
    { id: 'whisk-19', prompt: 'Subject: coffee shop interior, mood: relaxed, style: cozy aesthetic', description: 'Coffee shop' },
    { id: 'whisk-20', prompt: 'Subject: waterfall, mood: powerful, style: long exposure', description: 'Waterfall' },
    { id: 'whisk-21', prompt: 'Subject: vintage car, mood: classic, style: automotive photography', description: 'Vintage car' },
    { id: 'whisk-22', prompt: 'Subject: cherry blossoms, mood: serene, style: Japanese aesthetic', description: 'Cherry blossoms' },
    { id: 'whisk-23', prompt: 'Subject: lighthouse, mood: heroic, style: dramatic seascape', description: 'Lighthouse' },
    { id: 'whisk-24', prompt: 'Subject: fashion model, mood: confident, style: editorial', description: 'Fashion' },
    { id: 'whisk-25', prompt: 'Subject: fireworks, mood: celebratory, style: long exposure', description: 'Fireworks' }
  ],
  longPrompts: [
    { id: 'whisk-long-1', title: 'Complete Character', prompt: 'Subject: person portrait, mood: confident professional, style: headshot photography with studio lighting, detailed facial features, business attire, plain background', useCase: 'Professional' },
    { id: 'whisk-long-2', title: 'Product Photography', prompt: 'Subject: premium watch on marble, mood: luxurious, style: commercial product photography with dramatic lighting, sharp focus, reflection, minimalist composition', useCase: 'Product' },
    { id: 'whisk-long-3', title: 'Architectural', prompt: 'Subject: modern villa exterior, mood: aspirational, style: architectural photography at golden hour, wide angle, infinity pool, dramatic sky', useCase: 'Architecture' },
    { id: 'whisk-long-4', title: 'Fashion Editorial', prompt: 'Subject: fashion model in designer dress, mood: editorial, style: high fashion magazine editorial, dramatic pose, studio lighting, Vogue quality', useCase: 'Fashion' },
    { id: 'whisk-long-5', title: 'Food Photography', prompt: 'Subject: gourmet restaurant dish, mood: appetizing, style: food photography with bokeh, food styling, natural light, professional presentation', useCase: 'Food' },
    { id: 'whisk-long-6', title: 'Travel', prompt: 'Subject: influencer at destination, mood: wanderlust, style: travel photography, golden hour lighting, aspirational lifestyle, National Geographic style', useCase: 'Travel' },
    { id: 'whisk-long-7', title: 'Real Estate', prompt: 'Subject: luxury home interior, mood: aspirational, style: real estate photography, wide angle, warm lighting, staged professionally', useCase: 'Real Estate' },
    { id: 'whisk-long-8', title: 'Portrait', prompt: 'Subject: portrait with natural light, mood: intimate, style: portrait photography, 85mm lens, shallow depth of field, candid moment', useCase: 'Portrait' },
    { id: 'whisk-long-9', title: 'Abstract', prompt: 'Subject: abstract light patterns, mood: artistic, style: abstract photography, colorful, fluid shapes, contemporary art gallery aesthetic', useCase: 'Abstract' },
    { id: 'whisk-long-10', title: 'Lifestyle', prompt: 'Subject: lifestyle scene with products, mood: aspirational, style: lifestyle photography, flat lay构图, warm natural light, brand一致性', useCase: 'Lifestyle' },
    { id: 'whisk-long-11', title: 'Jewelry', prompt: 'Subject: jewelry on velvet, mood: luxurious, style: jewelry photography, macro details, sparkle, dark background, high-end luxury aesthetic', useCase: 'Jewelry' },
    { id: 'whisk-long-12', title: 'Automotive', prompt: 'Subject: sports car in studio, mood: powerful, style: automotive photography, dramatic lighting, studio setup, showroom quality', useCase: 'Automotive' },
    { id: 'whisk-long-13', title: 'Nature', prompt: 'Subject: wildlife in habitat, mood: majestic, style: wildlife photography, telephoto, natural behavior, National Geographic quality', useCase: 'Wildlife' },
    { id: 'whisk-long-14', title: 'Music', prompt: 'Subject: musician performing, mood: energetic, style: concert photography, stage lighting, dynamic pose, raw energy captured', useCase: 'Music' },
    { id: 'whisk-long-15', title: 'Fitness', prompt: 'Subject: fitness athlete training, mood: Powerful, style: sports photography, gym environment, dramatic lighting, motivated', useCase: 'Fitness' },
    { id: 'whisk-long-16', title: 'Beauty', prompt: 'Subject: beauty product close-up, mood: clean, style: beauty photography, macro, soft light, minimal aesthetic', useCase: 'Beauty' },
    { id: 'whisk-long-17', title: 'Wedding', prompt: 'Subject: wedding rings and flowers, mood: romantic, style: wedding photography, detail shot, soft light, emotional', useCase: 'Wedding' },
    { id: 'whisk-long-18', title: 'Corporate', prompt: 'Subject: corporate team, mood: professional, style: corporate headshot, business attire, clean background, team unity', useCase: 'Corporate' },
    { id: 'whisk-long-19', title: 'Artistic', prompt: 'Subject: artistic conceptual image, mood: thought-provoking, style: conceptual art, creative composition, gallery-worthy', useCase: 'Artistic' },
    { id: 'whisk-long-20', title: 'Social Media', prompt: 'Subject: Instagram-worthy moment, mood: aspirational, style: influencer photography, square composition, perfectly composed', useCase: 'Social Media' }
  ],
  faqs: [
    { question: 'What makes a good Google Whisk prompt?', answer: 'Follow pattern: "Subject: [what], mood: [feeling], style: [art style]". Be specific about your vision.' },
    { question: 'How is Google Whisk different from Midjourney?', answer: ' Whisk uses Google\'s Veo 3 for video and Veo 2 for images. Different AI model, different results. Try both!' },
    { question: 'Can I use these created images commercially?', answer: 'Check Google\'s terms. Generally personal and commercial use allowed with attribution.' },
    { question: 'What styles work best?', answer: 'Be specific: "cinematic lighting", "film photography", "oil painting", "3D render", "watercolor".' },
    { question: 'Why did my image not generate correctly?', answer: 'Try simpler prompts first. Break complex ideas into multiple generations. Add style after subject works.' },
    { question: 'How do I improve results?', answer: 'Add mood: "dramatic", "peaceful", "energetic". Add references: "like [artist name]". Iterate!' },
    { question: 'Can I combine two subjects?', answer: 'Yes! e.g., "Subject: cat in astronaut suit, mood: adventurous, style: playful".' },
    { question: 'What is the best resolution?', answer: 'Request specific in prompt: "high resolution", "8k", "detailed" for larger output.' }
  ],
  platformTips: [
    'Use the three-part format: Subject + Mood + Style',
    'Start simple, then add details in follow-up',
    'Be specific about lighting: "golden hour", "studio lighting"',
    'Add reference artists: "like [famous photographer]"',
    'Include composition: "wide angle", "macro", "close-up"',
    'Add mood words to set the feeling',
    'Experiment with different art styles',
    'Iterate on successful prompts for better results'
  ]
};