import { PromptPost } from './types';

export const gratitudeJournalPrompts: PromptPost = {
  slug: 'gratitude-journal-prompts',
  title: 'Gratitude Journal Prompts: 50+ Ways to Cultivate Thankfulness (2026)',
  keyword: 'gratitude journal prompts',
  description: 'Transform your life with gratitude journaling. 50+ prompts to cultivate thankfulness and positivity every day.',
  date: '2026-04-21',
  category: 'Self-Help',
  image: '/images/gratitude-journal-prompts.jpg',
  content: `<p>Start a daily <strong>gratitude practice</strong> with these powerful prompts to shift your mindset and increase happiness.</p>`,
  shortPrompts: [
    { id: 'gr-1', prompt: 'What are 3 things I\'m grateful for today?', description: 'Daily gratitude' },
    { id: 'gr-2', prompt: 'Who made me smile recently?', description: 'Person gratitude' },
    { id: 'gr-3', prompt: 'What simple pleasure enjoyed today?', description: 'Simple joys' },
    { id: 'gr-4', prompt: 'What is one thing my body allows me to do?', description: 'Body gratitude' },
    { id: 'gr-5', prompt: 'What challenge helped me grow?', description: 'Growth gratitude' },
    { id: 'gr-6', prompt: 'What technology makes life easier?', description: 'Tech thanks' },
    { id: 'gr-7', prompt: 'What memory brings me joy?', description: 'Memory gratitude' },
    { id: 'gr-8', prompt: 'What natural beauty did I notice today?', description: 'Nature gratitude' },
    { id: 'gr-9', prompt: 'Who helped me recently?', description: 'Support gratitude' },
    { id: 'gr-10', prompt: 'What meal am I grateful for?', description: 'Food gratitude' },
    { id: 'gr-11', prompt: 'What skill am I grateful to have?', description: 'Skill gratitude' },
    { id: 'gr-12', prompt: 'What home comfort do I appreciate?', description: 'Home gratitude' },
    { id: 'gr-13', prompt: 'What made me laugh recently?', description: 'Joy gratitude' },
    { id: 'gr-14', prompt: 'What opportunity am I grateful for?', description: 'Opportunity thanks' },
    { id: 'gr-15', prompt: 'What mistake taught me something?', description: 'Lesson gratitude' },
    { id: 'gr-16', prompt: 'Who inspires me?', description: 'Inspiration gratitude' },
    { id: 'gr-17', prompt: 'What music brightened my day?', description: 'Music gratitude' },
    { id: 'gr-18', prompt: 'What book or article helped me?', description: 'Learning gratitude' },
    { id: 'gr-19', prompt: 'What is beautiful right now?', description: 'Present beauty' },
    { id: 'gr-20', prompt: 'What health am I grateful for?', description: 'Health gratitude' },
    { id: 'gr-21', prompt: 'Who do I need to forgive and release?', description: 'Forgiveness practice' },
    { id: 'gr-22', prompt: 'What freedom do I have?', description: 'Freedom gratitude' },
    { id: 'gr-23', prompt: 'What small thing made today good?', description: 'Small joys' },
    { id: 'gr-24', prompt: 'What would I miss if it were gone?', description: 'Appreciation check' },
    { id: 'gr-25', prompt: 'What am I looking forward to?', description: 'Future gratitude' }
  ],
  longPrompts: [
    { id: 'gr-long-1', title: 'Letter of Gratitude', prompt: 'Write a letter to someone who positively impacted your life. Describe specific ways they helped and how you feel.', useCase: 'Relationship Building' },
    { id: 'gr-long-2', title: 'Gratitude for Past Self', prompt: 'Write to your past self from 5 years ago. Thank them for decisions and growth that benefit you now.', useCase: 'Self-Compassion' },
    { id: 'gr-long-3', title: 'Daily Abundance List', prompt: 'List 50 things you\'re grateful for. Include people, experiences, possessions, freedoms, and simple pleasures.', useCase: 'Abundance Mindset' },
    { id: 'gr-long-4', title: 'Gratitude Meditation', prompt: 'Write about someone you struggle to feel grateful for. Find 3 things to appreciate about them.', useCase: 'Expanding Gratitude' },
    { id: 'gr-long-5', title: 'Body Gratitude', prompt: 'Write a letter of appreciation to your body. Thank each part for what it does for you.', useCase: 'Body Acceptance' },
    { id: 'gr-long-6', title: 'Gratitude for Challenges', prompt: 'Write about 3 hard situations that ultimately helped you grow. How did they shape you?', useCase: 'Growth Mindset' },
    { id: 'gr-long-7', title: 'Season of Life', prompt: 'Write about your current life season. What are you grateful for? What do you look forward to?', useCase: 'Present Focus' },
    { id: 'gr-long-8', title: 'Sensory Gratitude', prompt: 'Write about 5 things you\'re grateful for that you experience through your senses: see, hear, smell, taste, touch.', useCase: 'Mindfulness' },
    { id: 'gr-long-9', title: 'Gratitude for Nature', prompt: 'Write about elements of nature you\'re grateful for. Trees, weather, seasons, animals - what brings you peace?', useCase: 'Nature Connection' },
    { id: 'gr-long-10', title: 'Career Gratitude', prompt: 'Write about aspects of your work you\'re grateful for. Colleagues, skills, opportunities, growth.', useCase: 'Work Appreciation' },
    { id: 'gr-long-11', title: 'Gratitude for Relationships', prompt: 'Write about 5 important relationships. What specific value does each person bring to your life?', useCase: 'Relationship Inventory' },
    { id: 'gr-long-12', title: 'Morning Gratitude Practice', prompt: 'Write about what a morning ritual could include. What would you appreciate waking up to daily?', useCase: 'Routine Design' },
    { id: 'gr-long-13', title: 'Gratitude for Learning', prompt: 'Write about 5 things you\'ve learned that you\'re grateful for. How did they change your life?', useCase: 'Growth Appreciation' },
    { id: 'gr-long-14', title: 'Little Things', prompt: 'Write about 20 small things that bring joy: a warm bed, morning coffee, a text from a friend. Savor each.', useCase: 'Savoring Practice' },
    { id: 'gr-long-15', title: 'Gratitude for Overcoming', prompt: 'Write about something you\'ve overcome. What strengths did you discover? What helped you?', useCase: 'Resilience Focus' },
    { id: 'gr-long-16', title: 'Gratitude Letter to Self', prompt: 'Write a letter to yourself appreciating your own qualities, efforts, and growth. Be kind.', useCase: 'Self-Love' },
    { id: 'gr-long-17', title: 'Gratitude for Home', prompt: 'Write about elements of your home you\'re grateful for. Create a sanctuary appreciation list.', useCase: 'Home Love' },
    { id: 'gr-long-18', title: 'Future Gratitude', prompt: 'Write as if it\'s one year from now. What are you grateful for that doesn\'t exist yet?', useCase: 'Vision Setting' },
    { id: 'gr-long-19', title: 'Music Gratitude', prompt: 'Write about music you\'re grateful for. What songs mark seasons of your life? How does music help you?', useCase: 'Music Appreciation' },
    { id: 'gr-long-20', title: 'Overall Life Gratitude', prompt: 'Write a comprehensive gratitude inventory: all aspects of life where you experience gratitude. Leave none out.', useCase: 'Complete Review' }
  ],
  faqs: [
    { question: 'How often should I practice gratitude journaling?', answer: 'Daily is ideal, but even 3 times weekly builds the habit. Consistency matters most.' },
    { question: 'What if I don\'t feel grateful?', answer: 'Start small. Even "I\'m grateful I have a bed to sleep in" builds the muscle. Eventually, you see more to appreciate.' },
    { question: 'Does it really change mindset?', answer: 'Yes! Research shows regular gratitude practice increases happiness, improves relationships, and reduces depression.' },
    { question: 'Should I write the same things?', answer: 'New discoveries daily. Train your brain to find new things. If stuck, repeat - that\'s still gratitude.' },
    { question: 'How long should entries be?', answer: 'Quality over quantity. 3 things daily takes 2 minutes. Longer weekly reflection develops depth.' },
    { question: 'Can I use bullet points?', answer: 'Absolutely! Lists, paragraphs, drawings - any format that helps you appreciate.' },
    { question: 'What if my life feels hard right now?', answer: 'Gratitude journaling during difficulty builds resilience. Even small things matter more.' },
    { question: 'Should I share my gratitude practice?', answer: 'Sharing can be powerful. Tell people you appreciate them. But private journaling has its own power.' }
  ],
  platformTips: [
    'Write first thing in the morning to set a positive tone',
    'Keep your journal where you\'ll see it daily',
    'Try 3 things format: one big, one medium, one small',
    'Include people in your gratitude regularly',
    'Review past entries to see abundance you may miss',
    'Set a phone reminder if you forget',
    'Share gratitude with others - it spreads positivity',
    'Don\'t force it - let it flow naturally'
  ]
};