import { PromptPost } from './types';

export const hingePrompts: PromptPost = {
  slug: 'hinge-prompts',
  title: 'Hinge Prompts for Guys: 50+ Best Answers That Get Matches (2026)',
  keyword: 'hinge prompts for guys',
  description: 'Master Hinge prompts with proven answers. Get more matches.',
  date: '2026-04-21',
  category: 'Dating',
  image: '/images/hinge-prompts.jpg',
  content: `<p>Get more matches with these <strong>best Hinge prompts for guys</strong>. Answer with personality and specificity.</p>`,
  shortPrompts: [
    { id: 'hp-1', prompt: 'My simple pleasures: Your answer - be specific', description: 'Simple pleasures' },
    { id: 'hp-2', prompt: 'If I could get a tattoo, it would be... Creativity shows', description: 'Tattoo answer' },
    { id: 'hp-3', prompt: 'A fact about me my friends would be surprised by...', description: 'Surprise fact' },
    { id: 'hp-4', prompt: 'The most underrated thing about your city is...', description: 'Local knowledge' },
    { id: 'hp-5', prompt: 'Ideal Friday night: Be specific, not generic', description: 'Friday night' },
    { id: 'hp-6', prompt: 'My go-to order at favorite restaurant:', description: 'Food answer' },
    { id: 'hp-7', prompt: 'I am overly competitive about... Be honest', description: 'Competitive' },
    { id: 'hp-8', prompt: 'A trend I am tired of: Be relatable', description: 'Trends' },
    { id: 'hp-9', prompt: 'If you need help with anything, I am your guy for...', description: 'Helpful' },
    { id: 'hp-10', prompt: 'My Sunday ritual: Show routine', description: 'Sunday ritual' },
    { id: 'hp-11', prompt: 'The most underrated thing about: Your philosophy', description: 'Dating philosophy' },
    { id: 'hp-12', prompt: 'My type: Be specific but not shallow', description: 'Type' },
    { id: 'hp-13', prompt: 'If I could be any animal, I would be... Why?', description: 'Animal' },
    { id: 'hp-14', prompt: 'My greatest fear: Be vulnerable', description: 'Fear' },
    { id: 'hp-15', prompt: 'I am weirdly good at: Unique skill', description: 'Weird skill' },
    { id: 'hp-16', prompt: 'My actual personality as a dog breed would be...', description: 'Dog breed' },
    { id: 'hp-17', prompt: 'Unpopular opinion: Be respectful', description: 'Unpopular' },
    { id: 'hp-18', prompt: 'My green flags: Show values', description: 'Green flags' },
    { id: 'hp-19', prompt: 'Most spontaneous thing I have done: Show range', description: 'Spontaneous' },
    { id: 'hp-20', prompt: 'The date I would plan: Be specific and creative', description: 'Date idea' },
    { id: 'hp-21', prompt: 'My love language in one word:', description: 'Love language' },
    { id: 'hp-22', prompt: 'If I ghosted you, it would be because... Humor', description: 'Humor' },
    { id: 'hp-23', prompt: 'One story you should definitely ask me about:', description: 'Story prompt' },
    { id: 'hp-24', prompt: 'My biggest life hack:', description: 'Life hack' },
    { id: 'hp-25', prompt: 'The way to win me over:', description: 'Win over' }
  ],
  longPrompts: [
    { id: 'hp-long-21', title: 'My Simple Pleasures', prompt: 'Specific answer. Avoid: generic things.', useCase: 'Simple Pleasures' },
    { id: 'hp-long-2', title: 'Ideal Friday Night', prompt: 'Specific. Show personality, leave opening.', useCase: 'Friday Night' },
    { id: 'hp-long-3', title: 'Green Flags', prompt: 'Values-based. Shows what you value in a partner.', useCase: 'Green Flags' },
    { id: 'hp-long-4', title: 'A Fact Surprising', prompt: 'Reveal something interesting.', useCase: 'Surprise Fact' },
    { id: 'hp-long-5', title: 'Date Idea', prompt: 'Creative and specific. Shows planning.', useCase: 'Date Idea' },
    { id: 'hp-long-6', title: 'Most Spontaneous', prompt: 'Show range. Shows you are not boring.', useCase: 'Spontaneous' },
    { id: 'hp-long-7', title: 'Story to Ask About', prompt: 'Pique interest. Show you have stories.', useCase: 'Story Hook' },
    { id: 'hp-long-8', title: 'Unpopular Opinion', prompt: 'Respectful but real. Avoid controversial topics.', useCase: 'Unpopular' },
    { id: 'hp-long-9', title: 'Most Underrated', prompt: 'Local knowledge. Show you know your city.', useCase: 'Local' },
    { id: 'hp-long-10', title: 'Things I am Good At', prompt: 'Specific skill. Show competence.', useCase: 'Skills' },
    { id: 'hp-long-11', title: 'My Greatest Fear', prompt: 'Vulnerability but not scary.', useCase: 'Fear' },
    { id: 'hp-long-12', title: 'Things I am Competitive About', prompt: 'Be honest.', useCase: 'Competitive' },
    { id: 'hp-long-13', title: 'Simple Question', prompt: 'Opener. Works - shows interest.', useCase: 'Question' },
    { id: 'hp-long-14', title: 'I am Known For', prompt: 'Friends perspective. Show how you show up.', useCase: 'Reputation' },
    { id: 'hp-long-15', title: 'Dating Philosophy', prompt: 'Your approach. Vibes over resume.', useCase: 'Philosophy' },
    { id: 'hp-long-16', title: 'Type Answer', prompt: 'Specific and confident.', useCase: 'Type' },
    { id: 'hp-long-17', title: 'Sunday Ritual', prompt: 'Show routine.', useCase: 'Sunday' },
    { id: 'hp-long-18', title: 'Tattoo Idea', prompt: 'Meaningful or funny.', useCase: 'Tattoo' },
    { id: 'hp-long-19', title: 'Dream Partner', prompt: 'Values.', useCase: 'Dream' },
    { id: 'hp-long-20', title: 'First Date Energy', prompt: 'Set the tone.', useCase: 'Energy' }
  ],
  faqs: [
    { question: 'Should I use humor in prompts?', answer: 'Yes. Humor shows personality and makes you memorable.' },
    { question: 'How often should I change prompts?', answer: 'Try new prompts monthly. Test what gets engagement.' },
    { question: 'What if I am not funny?', answer: 'Do not be funny. Authentic beats forced humor.' },
    { question: 'Should prompts be long or short?', answer: 'Medium - fill space but not all characters.' },
    { question: 'Can I use the same prompt everywhere?', answer: 'No. Customize for each app.' },
    { question: 'Should I mention my job?', answer: 'Only if it is interesting or unique.' },
    { question: 'What about politics?', answer: 'Avoid in prompts. Later is fine.' },
    { question: 'How do I stand out?', answer: 'Be specific. Be authentic. Show personality.' }
  ],
  platformTips: [
    'Be SPECIFIC: Thai food not food',
    'Show personality: humor, values',
    'Include conversation starters',
    'Avoid generic answers',
    'Let your authentic voice show',
    'Vulnerability builds connection',
    'Update prompts monthly',
    'Test and iterate'
  ]
};