import { PromptPost } from './types';

export const journalPromptsKids: PromptPost = {
  slug: 'journal-prompts-for-kids',
  title: 'Journal Prompts for Kids: 50+ Feelings & Thoughts (2026)',
  keyword: 'journal prompts for kids',
  description: '50+ simple journal prompts for kids to express feelings, dreams, and daily thoughts.',
  date: '2026-04-21',
  category: 'Kids',
  image: '/images/journal-prompts-kids.jpg',
  content: `<p>These simple <strong>journal prompts for kids</strong> help express feelings and explore imagination.</p>`,
  shortPrompts: [
    { id: 'jk-1', prompt: 'How are you feeling right now? Draw or write.', description: 'Feelings check' },
    { id: 'jk-2', prompt: 'What made you smile today?', description: 'Smile moment' },
    { id: 'jk-3', prompt: 'What was the best part of your day?', description: 'Best part' },
    { id: 'jk-4', prompt: 'What are you thankful for today?', description: 'Gratitude' },
    { id: 'jk-5', prompt: 'What do you want to be when you grow up?', description: 'Future dreams' },
    { id: 'jk-6', prompt: 'What makes you feel brave?', description: 'Bravery' },
    { id: 'jk-7', prompt: 'What is your favorite thing about yourself?', description: 'Favorite self' },
    { id: 'jk-8', prompt: 'What do you like most about school?', description: 'School likes' },
    { id: 'jk-9', prompt: 'If you could change one thing, what would it be?', description: 'Wishes' },
    { id: 'jk-10', prompt: 'What makes your family special?', description: 'Family love' },
    { id: 'jk-11', prompt: 'What do you love to do for fun?', description: 'Fun things' },
    { id: 'jk-12', prompt: 'What makes you feel safe?', description: 'Safety' },
    { id: 'jk-13', prompt: 'What did you learn today?', description: 'Learning' },
    { id: 'jk-14', prompt: 'What is your favorite memory?', description: 'Favorite memory' },
    { id: 'jk-15', prompt: 'How would you describe yourself to someone?', description: 'Self description' },
    { id: 'jk-16', prompt: 'What are you good at?', description: 'Strengths' },
    { id: 'jk-17', prompt: 'What do you hope for tomorrow?', description: 'Tomorrow hopes' },
    { id: 'jk-18', prompt: 'What makes you feel loved?', description: 'Love feeling' },
    { id: 'jk-19', prompt: 'What is your favorite place?', description: 'Favorite place' },
    { id: 'jk-20', prompt: 'What makes you unique?', description: 'Uniqueness' },
    { id: 'jk-21', prompt: 'If you could help the world, how?', description: 'World help' },
    { id: 'jk-22', prompt: 'What do you love most about your best friend?', description: 'Friend love' },
    { id: 'jk-23', prompt: 'What makes you feel proud?', description: 'Pride' },
    { id: 'jk-24', prompt: 'What is your favorite animal?', description: 'Favorite animal' },
    { id: 'jk-25', prompt: 'Who is your hero and why?', description: 'Hero' }
  ],
  longPrompts: [
    { id: 'jk-long-1', title: 'My Feelings Journal', prompt: 'Write or draw about your feelings today. What made you feel happy? What made you feel sad? What made you feel excited? Don\'t worry about perfect words.', useCase: 'Feelings' },
    { id: 'jk-long-2', title: 'A Letter to Future Me', prompt: 'Write a letter to yourself 1 year from now. What do you want to tell yourself? What do you hope to be doing? What advice do you have?', useCase: 'Future Self' },
    { id: 'jk-long-3', title: 'My Dream Day', prompt: 'Describe your perfect day from waking up to bedtime. Who is there? What do you do? How do you feel? Make it as detailed as you want.', useCase: 'Dream Day' },
    { id: 'jk-long-4', title: 'If I Could...', prompt: 'If you could have any superpower for one day, what would it be? How would you use it? Who would you help?', useCase: 'Superpower' },
    { id: 'jk-long-5', title: 'My Family Story', prompt: 'Write about your family. Who is in it? What do you love doing together? What makes your family special?', useCase: 'Family' },
    { id: 'jk-long-6', title: 'Things I Want My Teacher to Know', prompt: 'Write things you want your teacher to know. What do you like about class? What helps you learn? What do you wish was different?', useCase: 'Teacher Letter' },
    { id: 'jk-long-7', title: 'My Best Day Ever', prompt: 'Write about the best day you ever had. What happened? Who was there? Why was it the best? How did you feel?', useCase: 'Best Day' },
    { id: 'jk-long-8', title: 'When I Grow Up', prompt: 'When you grow up, what do you want to be? Why did you pick that? What steps could you take now to get there?', useCase: 'Growing Up' },
    { id: 'jk-long-9', title: 'My Friend Story', prompt: 'Write about your best friend. How did you meet? What do you like to do together? Why are they a good friend?', useCase: 'Friends' },
    { id: 'jk-long-10', title: 'Things I Am Good At', prompt: 'Write about things you are good at. Give examples. How did you get good at them? What makes you proud?', useCase: 'Strengths' },
    { id: 'jk-long-11', title: 'If I Ruled the World', prompt: 'If you were in charge of the world, what would you change? What would you make sure everyone has?', useCase: 'World' },
    { id: 'jk-long-12', title: 'My Proud Moment', prompt: 'Write about a time you felt really proud. What did you do? Who was there? How did it feel?', useCase: 'Proud' },
    { id: 'jk-long-13', title: 'My Sad Feelings', prompt: 'Write about a time you felt sad. What happened? How did you feel? What helped you feel better? It\'s okay to feel sad.', useCase: 'Sad' },
    { id: 'jk-long-14', title: 'My Happy Place', prompt: 'Describe your happy place. Where is it? What does it look like? How does it feel when you\'re there?', useCase: 'Happy Place' },
    { id: 'jk-long-15', title: 'My Scary Feelings', prompt: 'Write about something that scares you. Why does it scare you? What could help you not be as scared?', useCase: 'Scary' },
    { id: 'jk-long-16', title: 'My Story', prompt: 'Write the story of your life so far. The big moments, the small moments, what matters to you.', useCase: 'My Story' },
    { id: 'jk-long-17', title: 'A Story About My Pet', prompt: 'If you have a pet, write about them. If you don\'t, write about a pet you wish you had.', useCase: 'Pet' },
    { id: 'jk-long-18', title: 'My Opinion On...', prompt: 'Pick a topic you care about and write what you think. Kids can have opinions and they matter.', useCase: 'Opinion' },
    { id: 'jk-long-19', title: 'Someone I Look Up To', prompt: 'Write about someone you look up to. Who are they? Why do you admire them? What would you ask them?', useCase: 'Admire' },
    { id: 'jk-long-20', title: 'Next Year Goals', prompt: 'What do you want to do or learn next year? How could you work on it? Who could help?', useCase: 'Goals' }
  ],
  faqs: [
    { question: 'How do I start journaling?', answer: 'Just write or draw whatever you feel. No rules. Both work.' },
    { question: 'What if I do not know what to write?', answer: 'Pick a prompt that interests you.' },
    { question: 'Can I draw instead of writing?', answer: 'Absolutely. Drawings are wonderful.' },
    { question: 'Should I write every day?', answer: 'Any amount is great. Just try sometimes.' },
    { question: 'What if my feelings are mixed?', answer: 'It is okay to have mixed feelings.' },
    { question: 'Is it okay to write about sad things?', answer: 'Yes. Writing about all feelings helps.' },
    { question: 'What if someone reads my journal?', answer: 'Keep it private if you want. Your journal.' },
    { question: 'Is there a wrong way?', answer: 'No. There is no wrong way.' }
  ],
  platformTips: [
    'Make it a calm, quiet time',
    'Keep your journal special and private',
    'Use pictures if words are hard',
    'Don\'t worry about mistakes',
    'Draw how you feel',
    'Be honest - it\'s yours',
    'Date every entry',
    'Look back sometimes to see growth'
  ]
};