import { PromptPost } from './types';

export const journalingPrompts: PromptPost = {
  slug: 'journaling-prompts',
  title: 'Journaling Prompts: 50+ Ideas for Self-Discovery (2026)',
  keyword: 'journaling prompts',
  description: 'Discover 50+ powerful journaling prompts for self-reflection and personal growth.',
  date: '2026-04-21',
  category: 'Self-Help',
  image: '/images/journaling-prompts.jpg',
  content: `<p>Transform your journaling practice with these <strong>journaling prompts</strong> designed for self-discovery and personal growth.</p>`,
  shortPrompts: [
    { id: 'jl-1', prompt: 'What am I grateful for today?', description: 'Gratitude practice' },
    { id: 'jl-2', prompt: 'What made me smile today?', description: 'Moment of joy' },
    { id: 'jl-3', prompt: 'What is one thing I learned today?', description: 'Daily learning' },
    { id: 'jl-4', prompt: 'How am I feeling right now, honestly?', description: 'Emotional check-in' },
    { id: 'jl-5', prompt: 'What would my ideal day look like?', description: 'Vision building' },
    { id: 'jl-6', prompt: 'What fear do I want to overcome?', description: 'Fear exploration' },
    { id: 'jl-7', prompt: 'Who made a positive impact on my life?', description: 'Appreciation' },
    { id: 'jl-8', prompt: 'What habit do I want to build?', description: 'Habit planning' },
    { id: 'jl-9', prompt: 'What does success mean to me?', description: 'Values clarification' },
    { id: 'jl-10', prompt: 'What boundaries do I need to set?', description: 'Boundary identification' },
    { id: 'jl-11', prompt: 'What is holding me back?', description: 'Obstacle identification' },
    { id: 'jl-12', prompt: 'What would I do if I could not fail?', description: 'Dream exploration' },
    { id: 'jl-13', prompt: 'What does my future self want to tell me?', description: 'Future self-letter' },
    { id: 'jl-14', prompt: 'What story am I telling myself?', description: 'Self-narrative' },
    { id: 'jl-15', prompt: 'What brings me peace?', description: 'Peace identification' },
    { id: 'jl-16', prompt: 'What am I avoiding?', description: 'Avoidance exploration' },
    { id: 'jl-17', prompt: 'What makes me feel alive?', description: 'Vitality mapping' },
    { id: 'jl-18', prompt: 'What relationship needs attention?', description: 'Relationship focus' },
    { id: 'jl-19', prompt: 'What would I do with one extra hour daily?', description: 'Time exploration' },
    { id: 'jl-20', prompt: 'What does self-care look like for me?', description: 'Self-care definition' },
    { id: 'jl-21', prompt: 'What challenge am I facing?', description: 'Challenge acknowledgment' },
    { id: 'jl-22', prompt: 'What memory do I treasure most?', description: 'Memory lane' },
    { id: 'jl-23', prompt: 'What would I change about my day?', description: 'Day reflection' },
    { id: 'jl-24', prompt: 'What am I proud of?', description: 'Proud moments' },
    { id: 'jl-25', prompt: 'What do I need to forgive myself for?', description: 'Self-forgiveness' }
  ],
  longPrompts: [
    { id: 'jl-long-1', title: 'Life Chapter Review', prompt: 'Write about a chapter of your life that has recently closed. What did you learn?', useCase: 'Life Reflection' },
    { id: 'jl-long-2', title: 'Letter to Your Younger Self', prompt: 'Write a letter to yourself from 10 years ago. What would you tell them?', useCase: 'Self-Compassion' },
    { id: 'jl-long-3', title: 'Values Deep Dive', prompt: 'List your top 5 values. Write about when you lived these values and when you did not.', useCase: 'Values Exploration' },
    { id: 'jl-long-4', title: 'Fear Mapping', prompt: 'Write about your biggest fears. Where did they come from? Are they serving you?', useCase: 'Fear Work' },
    { id: 'jl-long-5', title: 'Perfect Day Visualization', prompt: 'Describe your perfect day in detail. What do you do? Who is there?', useCase: 'Vision Setting' },
    { id: 'jl-long-6', title: 'Relationship Inventory', prompt: 'Write about the important relationships in your life. What role does each play?', useCase: 'Relationship Review' },
    { id: 'jl-long-7', title: 'Stress Source Analysis', prompt: 'What stresses you most right now? Write what you can control and one action step.', useCase: 'Stress Management' },
    { id: 'jl-long-8', title: 'Dream Exploration', prompt: 'If you could wake up tomorrow and your life was perfect, what would be different?', useCase: 'Dream Discovery' },
    { id: 'jl-long-9', title: 'Money Mindset', prompt: 'Write about your relationship with money. What beliefs did you grow up with?', useCase: 'Mindset Work' },
    { id: 'jl-long-10', title: 'Body Appreciation', prompt: 'Write a letter of appreciation to your body. What has it done for you?', useCase: 'Body Love' },
    { id: 'jl-long-11', title: 'Career Reflection', prompt: 'Are you on the right career path? Write what excites you and what drains you.', useCase: 'Career Review' },
    { id: 'jl-long-12', title: 'Forgiveness Practice', prompt: 'Who do you need to forgive? Write about what freedom forgiveness would bring.', useCase: 'Forgiveness Work' },
    { id: 'jl-long-13', title: 'Identity Exploration', prompt: 'Who are you? Write descriptors: roles, traits, beliefs.', useCase: 'Identity Work' },
    { id: 'jl-long-14', title: 'Gratitude Deep Dive', prompt: 'Write 10 things you are grateful for with explanations.', useCase: 'Gratitude Practice' },
    { id: 'jl-long-15', title: 'Growth Edges', prompt: 'What area of your life needs growth? Write about one small step to address it.', useCase: 'Personal Growth' },
    { id: 'jl-long-16', title: 'Inner Critic Dialogue', prompt: 'What does your inner critic say? Then respond as your wisest self.', useCase: 'Inner Work' },
    { id: 'jl-long-17', title: 'Joy Collection', prompt: 'What brings you joy? List small and big joys.', useCase: 'Joy Mapping' },
    { id: 'jl-long-18', title: 'Life Lessons', prompt: 'Write about a difficult life lesson. How did it change you?', useCase: 'Wisdom Gathering' },
    { id: 'jl-long-19', title: 'Morning Routine Vision', prompt: 'Design your ideal morning routine. What would make mornings special?', useCase: 'Routine Design' },
    { id: 'jl-long-20', title: 'Legacy Writing', prompt: 'What do you want to be remembered for?', useCase: 'Legacy Planning' }
  ],
  faqs: [
    { question: 'How do I start journaling if I have never done it?', answer: 'Start with just 5 minutes. Write whatever comes to mind. No rules, just write.' },
    { question: 'What if I do not know what to write about?', answer: 'Use prompts! They are here to help. Even I do not know is worth writing about.' },
    { question: 'Should I journal every day?', answer: 'Aim for consistency, but flexibility matters more. Any journaling beats none.' },
    { question: 'What if someone reads my journal?', answer: 'Keep it private if needed. Use a password-protected app. Your journal is for you.' },
    { question: 'Is there a right way to journal?', answer: 'No wrong way! Lists, paragraphs, drawings - whatever works for you is right.' },
    { question: 'How do prompts help with self-discovery?', answer: 'Prompts ask questions you might not think to ask yourself.' },
    { question: 'Should I read old journal entries?', answer: 'Sometimes illuminating. If useful for context, yes.' },
    { question: 'What if I feel emotional while journaling?', answer: 'That is often the point! Let it out. Tears are welcome.' }
  ],
  platformTips: [
    'Set a specific time daily for journaling to build the habit',
    'Keep your journal private and safe',
    'Use prompts when stuck - they are tools, not tests',
    'Do not edit while writing - just let it flow',
    'Date every entry to track your journey',
    'Review past entries monthly to see patterns',
    'Try different formats: bullet lists, letters, poetry',
    'Do not worry about spelling or grammar'
  ]
};