import { PromptPost } from './types';

export const journalPromptsMentalHealth: PromptPost = {
  slug: 'journal-prompts-mental-health',
  title: 'Journal Prompts for Mental Health: 50+ Healing Questions (2026)',
  keyword: 'journal prompts for mental health',
  description: 'Powerful journaling prompts for mental health. Reduce anxiety, process emotions, and improve wellbeing through writing.',
  date: '2026-04-21',
  category: 'Mental Health',
  image: '/images/journal-prompts-mental-health.jpg',
  content: `<p>Use these <strong>mental health journaling prompts</strong> to process emotions, reduce anxiety, and support your wellbeing journey.</p>`,
  shortPrompts: [
    { id: 'mh-1', prompt: 'How am I really feeling right now?', description: 'Emotional check-in' },
    { id: 'mh-2', prompt: 'What is causing me stress today?', description: 'Stress identification' },
    { id: 'mh-3', prompt: 'What would I tell a friend in my situation?', description: 'Self-compassion' },
    { id: 'mh-4', prompt: 'What does rest look like for me?', description: 'Rest definition' },
    { id: 'mh-5', prompt: 'What boundary do I need to set?', description: 'Boundary work' },
    { id: 'mh-6', prompt: 'What is my inner critic saying?', description: 'Inner voice awareness' },
    { id: 'mh-7', prompt: 'What brings me comfort?', description: 'Comfort mapping' },
    { id: 'mh-8', prompt: 'What am I holding onto that I need to release?', description: 'Letting go' },
    { id: 'mh-9', prompt: 'What small win can I celebrate?', description: 'Win acknowledgment' },
    { id: 'mh-10', prompt: 'What do I need right now?', description: 'Needs assessment' },
    { id: 'mh-11', prompt: 'What am I avoiding?', description: 'Avoidance exploration' },
    { id: 'mh-12', prompt: 'What triggers my anxiety?', description: 'Trigger identification' },
    { id: 'mh-13', prompt: 'Who makes me feel safe?', description: 'Safety mapping' },
    { id: 'mh-14', prompt: 'What does my ideal peaceful day look like?', description: 'Peace vision' },
    { id: 'mh-15', prompt: 'What thought pattern keeps recurring?', description: 'Pattern awareness' },
    { id: 'mh-16', prompt: 'What am I proud of myself for?', description: 'Pride practice' },
    { id: 'mh-17', prompt: 'What does self-care look like for me today?', description: 'Daily self-care' },
    { id: 'mh-18', prompt: 'What is one thing I can control right now?', description: 'Control focus' },
    { id: 'mh-19', prompt: 'What would I do if I wasn\'t afraid?', description: 'Fear exploration' },
    { id: 'mh-20', prompt: 'How did I show strength today?', description: 'Strength recognition' },
    { id: 'mh-21', prompt: 'What relationship drains or supports me?', description: 'Energy mapping' },
    { id: 'mh-22', prompt: 'What am I grateful for in this hard moment?', description: 'Hard moment gratitude' },
    { id: 'mh-23', prompt: 'What does my body need?', description: 'Body needs' },
    { id: 'mh-24', prompt: 'What would my future healed self say?', description: 'Future self wisdom' },
    { id: 'mh-25', prompt: 'Is there anyone I need to forgive?', description: 'Forgiveness work' }
  ],
  longPrompts: [
    { id: 'mh-long-1', title: 'Anxiety Exploration', prompt: 'Write about what\'s causing anxiety. When did it start? What triggers it? What helps? Be completely honest.', useCase: 'Anxiety Processing' },
    { id: 'mh-long-2', title: 'Letter to Your Anxiety', prompt: 'Write a letter to your anxiety as if it were a person. What would you say? How has it tried to protect you?', useCase: 'Anxiety Relationship' },
    { id: 'mh-long-3', title: 'Childhood Joy', prompt: 'Remember being young and carefree. What made you happy? How can you bring some of that joy to your life now?', useCase: 'Joy Recovery' },
    { id: 'mh-long-4', title: 'Permission to Feel', prompt: 'Give yourself permission to feel your hardest emotions. Write them out without judgment. They\'re valid.', useCase: 'Emotional Validation' },
    { id: 'mh-long-5', title: 'Healing Timeline', prompt: 'Write your emotional healing timeline. What hurt? What helped? What still needs work?', useCase: 'Healing Journey' },
    { id: 'mh-long-6', title: 'Inner Child Letter', prompt: 'Write to your inner child. What do they need to hear? What wounds need healing?', useCase: 'Inner Child Work' },
    { id: 'mh-long-7', title: 'Worst Case Scenario', prompt: 'Write out your worst fear in detail. Then write: even if this happens, I will...', useCase: 'Fear Facing' },
    { id: 'mh-long-8', title: 'Boundaries Inventory', prompt: 'What boundaries do you need? What happens when they\'re crossed? How can you enforce them?', useCase: 'Boundary Setting' },
    { id: 'mh-long-9', title: 'Daily Stress Analysis', prompt: 'Map out your day: what drained energy? What gave energy? How can you adjust?', useCase: 'Energy Management' },
    { id: 'mh-long-10', title: 'Comparison Trap', prompt: 'Who do you compare yourself to? What would life look like if you stopped comparing?', useCase: 'Comparison Release' },
    { id: 'mh-long-11', title: 'Sleep Journal', prompt: 'How have you been sleeping? What does your mind do at night? What bedtime routine would help?', useCase: 'Sleep Health' },
    { id: 'mh-long-12', title: 'People Pleasing Pattern', prompt: 'When do you people please? What are you afraid of if you say no? What would change if you prioritized yourself?', useCase: 'People Pleasing Recovery' },
    { id: 'mh-long-13', title: 'Body-Mind Connection', prompt: 'How does your body hold stress? What sensations come with hard emotions? How can you release them?', useCase: 'Somatic Awareness' },
    { id: 'mh-long-14', title: 'Negative Self-Talk', prompt: 'Write your most common negative thoughts. Then respond with what a kind friend would say.', useCase: 'Cognitive Reframing' },
    { id: 'mh-long-15', title: 'Life Satisfaction Audit', prompt: 'Rate satisfaction in: career, relationships, health, growth, fun. What needs attention?', useCase: 'Life Review' },
    { id: 'mh-long-16', title: 'Social Media Impact', prompt: 'How does social media affect your mood? What accounts lift you? Which drain you?', useCase: 'Digital Wellbeing' },
    { id: 'mh-long-17', title: 'Support System', prompt: 'Who is in your support system? Who can you really open up to? Who do you need more from?', useCase: 'Support Mapping' },
    { id: 'mh-long-18', title: 'Control Release', prompt: 'Write what you cannot control. How can you practice accepting these things?', useCase: 'Control Release' },
    { id: 'mh-long-19', title: 'Grief Processing', prompt: 'What have you lost that you\'re still grieving? How has it changed you? What helps you remember?', useCase: 'Grief Work' },
    { id: 'mh-long-20', title: 'Values Living', prompt: 'What are your core values? Are you living in alignment with them? What changes are needed?', useCase: 'Values Alignment' }
  ],
  faqs: [
    { question: 'Can journaling really improve mental health?', answer: 'Yes! Research shows journaling reduces stress, improves mood, and helps process traumatic experiences.' },
    { question: 'What if I don\'t know what I\'m feeling?', answer: 'Start with body scanning: where do you feel tension? That often reveals emotion. Also try "I feel... nothing" - that\'s info.' },
    { question: 'Should I share my journal with my therapist?', answer: 'If it helps your work together, yes. But your journal is private - share only what feels right.' },
    { question: 'What if I cry while journaling?', answer: 'That\'s often the point! Tears release emotion. Keep a tissue nearby and let it out.' },
    { question: 'How do I start if I\'ve never journaled?', answer: 'Just 5 minutes: "I don\'t know what to write" is fine. Eventually prompts help unlock deeper thinking.' },
    { question: 'What if dark thoughts come up?', answer: 'Writing can surface difficult things. If thoughts are harmful or overwhelming, reach out to a professional.' },
    { question: 'Should I journal in the morning or night?', answer: 'Either! Morning clears the day. Night processes the day. Try both to see what fits.' },
    { question: 'Is there a wrong way to journal?', answer: 'No wrong way! Format doesn\'t matter. Just write authentically, even if messy or incomplete.' }
  ],
  platformTips: [
    'Set a consistent journaling time daily',
    'Create a calm space for journaling practice',
    'Use prompts when you feel stuck',
    'Don\'t edit - let thoughts flow freely',
    'Date every entry to track patterns over time',
    'Keep journals private and secure',
    'Review old entries to see growth',
    'Be patient - benefits compound over time'
  ]
};