import { PromptPost } from './types';

export const musicVideoPrompts: PromptPost = {
  slug: 'music-video-prompts',
  title: 'Music Video Prompts: 50+ AI Prompts for Epic Videos (2026)',
  keyword: 'music video prompts',
  description: 'Create stunning music videos with AI. 50+ prompts for Midjourney, Runway, and more.',
  date: '2026-04-21',
  category: 'Video',
  image: '/images/music-video-prompts.jpg',
  content: `<p>Generate creative <strong>music video concepts</strong> and storyboards with these AI prompts.</p>`,
  shortPrompts: [
    { id: 'mv-1', prompt: '/imagine prompt: concert stage, crowd hands up, dramatic lighting, energy --ar 16:9 --v 6', description: 'Concert energy' },
    { id: 'mv-2', prompt: '/imagine prompt: singer in rain, neon reflections, moody, cinematic --ar 16:9 --v 6', description: 'Rain scene' },
    { id: 'mv-3', prompt: '/imagine prompt: desert highway, car driving into sunset, freedom --ar 16:9 --v 6', description: 'Road trip' },
    { id: 'mv-4', prompt: '/imagine prompt: bedroom party, friends dancing, vibrant, fun --ar 16:9 --v 6', description: 'House party' },
    { id: 'mv-5', prompt: '/imagine prompt: abandoned warehouse, strobe lights, warehouse rave --ar 16:9 --v 6', description: 'Warehouse rave' },
    { id: 'mv-6', prompt: '/imagine prompt: beach bonfire, night, musicians playing, warm --ar 16:9 --v 6', description: 'Beach bonfire' },
    { id: 'mv-7', prompt: '/imagine prompt: city rooftop at night, skyline, artist performing --ar 16:9 --v 6', description: 'Rooftop' },
    { id: 'mv-8', prompt: '/imagine prompt: forest clearing, fairy lights, magical atmosphere --ar 16:9 --v 6', description: 'Forest magic' },
    { id: 'mv-9', prompt: '/imagine prompt: neon tunnel, walking slow motion, visual art --ar 16:9 --v 6', description: 'Neon tunnel' },
    { id: 'mv-10', prompt: '/imagine prompt: subway station, dancing, urban, gritty --ar 16:9 --v 6', description: 'Subway dance' },
    { id: 'mv-11', prompt: '/imagine prompt: hotel hallway, chase scene, thriller --ar 16:9 --v 6', description: 'Thriller' },
    { id: 'mv-12', prompt: '/imagine prompt: underwater, floating, ethereal, dreamlike --ar 16:9 --v 6', description: 'Underwater' },
    { id: 'mv-13', prompt: '/imagine prompt: retro 80s bedroom, synthesizers, vintage --ar 16:9 --v 6', description: '80s retro' },
    { id: 'mv-14', prompt: '/imagine prompt: desert, tarot cards floating, mystical --ar 16:9 --v 6', description: 'Mystical' },
    { id: 'mv-15', prompt: '/imagine prompt: empty theater, spotlight on stage, dramatic --ar 16:9 --v 6', description: 'Spotlight' },
    { id: 'mv-16', prompt: '/imagine prompt: neon signs, rain, reflection, cyberpunk --ar 16:9 --v 6', description: 'Cyberpunk rain' },
    { id: 'mv-17', prompt: '/imagine prompt: mountain peak, wind, dramatic, epic --ar 16:9 --v 6', description: 'Mountain epic' },
    { id: 'mv-18', prompt: '/imagine prompt: bedroom, waking up, soft morning light --ar 16:9 --v 6', description: 'Morning wake' },
    { id: 'mv-19', prompt: '/imagine prompt: train moving, passing landscape, travel --ar 16:9 --v 6', description: 'Train travel' },
    { id: 'mv-20', prompt: '/imagine prompt: underwater coral, colors, vibrant, music visualizer style --ar 16:9 --v 6', description: 'Coral colors' },
    { id: 'mv-21', prompt: '/imagine prompt: car trunk full of cash, luxe, rap video --ar 16:9 --v 6', description: 'Rap video' },
    { id: 'mv-22', prompt: '/imagine prompt: garden, couple slow dancing, romantic --ar 16:9 --v 6', description: 'Romantic dance' },
    { id: 'mv-23', prompt: '/imagine prompt: broken relationship, leaving house, emotional --ar 16:9 --v 6', description: 'Sad departure' },
    { id: 'mv-24', prompt: '/imagine prompt: party gone wrong, chaos, dramatic --ar 16:9 --v 6', description: 'Party chaos' },
    { id: 'mv-25', prompt: '/imagine prompt: crowd surf, mosh pit, energy --ar 16:9 --v 6', description: 'Mosh pit' }
  ],
  longPrompts: [
    { id: 'mv-long-21', title: 'Epic Concert Opening', prompt: '/imagine prompt: Massive concert stage opening, pyro going off, crowd in arena shot, stadium lights blaring, energy max, dramatic scale, rock concert aesthetic, epic --ar 16:9 --v 6', useCase: 'Concert' },
    { id: 'mv-long-2', title: 'Road Trip Narrative', prompt: '/imagine prompt: Road trip storyboard sequence: car driving, gas station stop, diner scene, desert night,目的地 arriving. Cinematic narrative flow, action-oriented --ar 16:9 --v 6', useCase: 'Narrative' },
    { id: 'mv-long-3', title: 'Breakup Story', prompt: '/imagine prompt: Full breakup storyboard: happy memories, argument, packing bags, walking out door, alone crying. Dramatic emotional storytelling, close-ups and wides --ar 16:9 --v 6', useCase: 'Breakup' },
    { id: 'mv-long-4', title: 'Dream Sequence', prompt: '/imagine prompt: Dream sequence: surreal floating buildings, melting clocks, impossible gravity, trippy colors, surrealist Salvador Dali inspired, --ar 16:9 --v 6', useCase: 'Dream' },
    { id: 'mv-long-5', title: 'One-Shot Wonder', prompt: '/imagine prompt: Single continuous shot concept: tracking through rooms, different scenes, seamless edit ready, long take aesthetic --ar 16:9 --v 6', useCase: 'One-shot' },
    { id: 'mv-long-6', title: 'Chromakey Storyboard', prompt: '/imagine prompt: Chromakey-ready storyboards: green screen friendly compositions, performer centered, room to add effects, video production ready --ar 16:9 --v 6', useCase: 'Green screen' },
    { id: 'mv-long-7', title: 'Retro VHS', prompt: '/imagine prompt: 90s VHS music video aesthetic, crt lines, tracking distortion, vintage camera look, nostalgia, grain --ar 16:9 --v 6', useCase: 'VHS' },
    { id: 'mv-long-8', title: 'Color Story', prompt: '/imagine prompt: Monochrome to color transition storyboard: black and white opening, color explosion finale, visual metamorphosis --ar 16:9 --v 6', useCase: 'Color' },
    { id: 'mv-long-9', title: 'Performance Video', prompt: '/imagine prompt: Clean performance video setup: band playing, good angles, stage lighting, solid foundation for editing --ar 16:9 --v 6', useCase: 'Performance' },
    { id: 'mv-long-10', title: 'Narrative Short', prompt: '/imagine prompt: Mini music film: opening scene, conflict, musical numbers, climax, resolution. Short film quality storytelling --ar 16:9 --v 6', useCase: 'Narrative' },
    { id: 'mv-long-11', title: 'Visualizer', prompt: '/imagine prompt: Audio visualizer style: abstract shapes responding to music, waveforms, equalizer bars, colorful abstract --ar 16:9 --v 6', useCase: 'Visualizer' },
    { id: 'mv-long-12', title: 'Fashion Forward', prompt: '/imagine prompt: High fashion music video: designer wardrobe, model performance, editorial quality, runway crossover, Vogue aesthetic --ar 16:9 --v 6', useCase: 'Fashion' },
    { id: 'mv-long-13', title: 'Social Message', prompt: '/imagine prompt: Meaningful narrative music video: social message story, emotional arc, powerful ending, documentary footage blend --ar 16:9 --v 6', useCase: 'Message' },
    { id: 'mv-long-14', title: 'Travel Documentary', prompt: '/imagine prompt: Travel documentary style music video: destination shots, local moments, wanderlust, cinematic travel photography --ar 16:9 --v 6', useCase: 'Travel' },
    { id: 'mv-long-15', title: 'Dance Video', prompt: '/imagine prompt: Full choreography music video: dancer performing, wide and close shots, clean background, studio quality, movement-oriented --ar 16:9 --v 6', useCase: 'Dance' },
    { id: 'mv-long-16', title: 'Lyric Video', prompt: '/imagine prompt: Lyric video ready: clean background, text space, visual loop, simple but engaging, text placement ready --ar 16:9 --v 6', useCase: 'Lyric Video' },
    { id: 'mv-long-17', title: 'Concept Album', prompt: '/imagine prompt: Album cover concept matching music: visual identity, series potential, branding consistent, vinyl-ready --ar 2:3 --v 6', useCase: 'Album' },
    { id: 'mv-long-18', title: 'Animated', prompt: '/imagine prompt: 2D animation style storyboard: keyframes for animation, clean lines, character designs ready for motion --ar 16:9 --v 6', useCase: 'Animation' },
    { id: 'mv-long-19', title: '360 Video', prompt: '/imagine prompt: 360 video composition: center-focused, all directions interesting, VR-ready composition --ar 1:1 --v 6', useCase: '360' },
    { id: 'mv-long-20', title: 'Vertical Video', prompt: '/imagine prompt: Vertical TikTok/shorts format music video: phone composition, vertical framing, short-form ready --ar 9:16 --v 6', useCase: 'Vertical' }
  ],
  faqs: [
    { question: 'Which AI tools create best music video frames?', answer: 'Midjourney for concept frames. Runway Gen-2 for actual video generation. Combine for best results.' },
    { question: 'Can I create full music videos with AI?', answer: 'Frame by frame: Yes. Use AI for storyboard, then video tools. Full generation improving rapidly.' },
    { question: 'What makes good music video prompts?', answer: 'Mood, lighting, composition, action.' },
    { question: 'How do I create a storyboard?', answer: 'Break video into key moments. Prompt each frame.' },
    { question: 'Should I use reference styles?', answer: 'Add like artist for reference. MTV 90s style guides tone.' },
    { question: 'Can AI generate lyrics overlay?', answer: 'Not directly. Add text space to prompts.' },
    { question: 'What aspect ratios work?', answer: '16:9 YouTube, 9:16 TikTok, 1:1 square.' },
    { question: 'How do I maintain consistency?', answer: 'Use same seed or base prompt.' }
  ],
  platformTips: [
    'Use consistent style across all frames',
    'Include "cinematic" or "dramatic lighting" for depth',
    'Add "storyboard" to get multi-panel output',
    'Design for your platform: YouTube vs TikTok',
    'Use "high resolution" for print/digital use',
    'Add reference: "like [music video style]"',
    'Include "chromakey" or "green screen" if needed',
    'Batch prompts for storyboard sequences'
  ]
};