import { PromptPost } from './types';

export const optomcasPrompts: PromptPost = {
  slug: 'optomcas-prompts',
  title: 'OptomCAS Prompts: 50+ OD School Application Essays (2026)',
  keyword: 'optomcas prompts',
  description: 'Master OptomCAS application with these powerful personal statement and essay prompts for optometry school.',
  date: '2026-04-21',
  category: 'Education',
  image: '/images/optomcas-prompts.jpg',
  content: `<p>Succeed in your <strong>OptomCAS application</strong> with these prompts for personal statements and essays.</p>`,
  shortPrompts: [
    { id: 'opt-1', prompt: 'Why do you want to become an optometrist?', description: 'Career motivation' },
    { id: 'opt-2', prompt: 'Describe a time you helped someone. How did it feel?', description: 'Service experience' },
    { id: 'opt-3', prompt: 'What does compassion in healthcare mean to you?', description: 'Values' },
    { id: 'opt-4', prompt: 'Describe a challenge you overcame. What did you learn?', description: 'Resilience' },
    { id: 'opt-5', prompt: 'Who inspired you to pursue eye care? How?', description: 'Influence' },
    { id: 'opt-6', prompt: 'What patient interaction changed your perspective?', description: 'Growth moment' },
    { id: 'opt-7', prompt: 'Describe your shadowing experience. What did you learn?', description: 'Shadowing' },
    { id: 'opt-8', prompt: 'How do you handle stress? Give an example.', description: 'Stress management' },
    { id: 'opt-9', prompt: 'What makes you unique as a candidate?', description: 'Differentiator' },
    { id: 'opt-10', prompt: 'Describe a leadership experience. What was your role?', description: 'Leadership' },
    { id: 'opt-11', prompt: 'What are your career goals in optometry?', description: 'Career vision' },
    { id: 'opt-12', prompt: 'How do you work with difficult people?', description: 'Teamwork' },
    { id: 'opt-13', prompt: 'Describe your volunteer experience. Impact?', description: 'Volunteerism' },
    { id: 'opt-14', prompt: 'What would you change about healthcare?', description: 'Healthcare vision' },
    { id: 'opt-15', prompt: 'Describe your best academic achievement. Why?', description: 'Academic' },
    { id: 'opt-16', prompt: 'How do you stay current in healthcare?', description: 'Learning' },
    { id: 'opt-17', prompt: 'Describe a time you advocated for someone.', description: 'Advocacy' },
    { id: 'opt-18', prompt: 'What role does ethics play in patient care?', description: 'Ethics' },
    { id: 'opt-19', prompt: 'How do you handle constructive criticism?', description: 'Feedback' },
    { id: 'opt-20', prompt: 'Describe your research experience. What did you learn?', description: 'Research' },
    { id: 'opt-21', prompt: 'What special populations do you want to serve?', description: 'Populations' },
    { id: 'opt-22', prompt: 'How do you balance work and life?', description: 'Balance' },
    { id: 'opt-23', prompt: 'Describe a time you failed and what you did.', description: 'Failure' },
    { id: 'opt-24', prompt: 'What do you hope patients remember about you?', description: 'Legacy' },
    { id: 'opt-25', prompt: 'Why should we choose you?', description: 'Pitch' }
  ],
  longPrompts: [
    { id: 'opt-long-1', title: 'Career Motivation Essay', prompt: 'Write about why you want to become an optometrist. Include: when did you first consider this career, what sealed the decision, what kind of optometrist you want to be, and why this specific moment matters.', useCase: 'Personal Statement' },
    { id: 'opt-long-2', title: 'Patient Care Experience', prompt: 'Describe a specific patient interaction that confirmed your career choice. Include: the setting, what happened, how it affected you, and what you learned about yourself.', useCase: 'Essay' },
    { id: 'opt-long-3', title: 'Diversity & Inclusion', prompt: 'Write about your commitment to serving diverse populations. Include: your background, experiences with diversity, specific populations you want to serve, and actionable plans.', useCase: 'Diversity' },
    { id: 'opt-long-4', title: 'Leadership Story', prompt: 'Describe a leadership role in detail. Include: the situation, your responsibilities, challenges faced, how you motivated others, and outcomes achieved.', useCase: 'Leadership' },
    { id: 'opt-long-5', title: 'Overcoming Adversity', prompt: 'Write about a significant challenge. Include: what happened, how it affected you, what you did, what you learned, and how it shapes you now.', useCase: 'Adversity' },
    { id: 'opt-long-6', title: 'Shadowing Reflection', prompt: 'Reflect on your observation hours. Include: what you saw, how it confirmed your interest, a specific moment that stood out, and what type of practice you envision.', useCase: 'Reflection' },
    { id: 'opt-long-7', title: 'Research Experience', prompt: 'Describe research involvement. Include: your role, methodology, findings, what you learned about research process, and how it applies to optometry.', useCase: 'Research' },
    { id: 'opt-long-8', title: 'Community Service', prompt: 'Write about meaningful volunteer work. Include: organization, your role, who you helped, personal growth, and continued commitment.', useCase: 'Service' },
    { id: 'opt-long-9', title: 'Teamwork Experience', prompt: 'Describe working in a team toward a goal. Include: your role, team dynamics, conflict and resolution, success, and your contributions.', useCase: 'Teamwork' },
    { id: 'opt-long-10', title: 'Future Goals', prompt: 'Outline your 5-year and 10-year career plans. Include: specialty interest, practice setting, continuing education, research goals, and how you give back.', useCase: 'Future' },
    { id: 'opt-long-11', title: 'Ethical Situation', prompt: 'Write about an ethical dilemma you faced. Include: the situation, your decision, why it was difficult, and how you would handle it now.', useCase: 'Ethics' },
    { id: 'opt-long-12', title: 'Personal Growth', prompt: 'Describe how you\'ve grown in the past 3 years. Include: specific examples, what drove change, challenges, and current strengths.', useCase: 'Growth' },
    { id: 'opt-long-13', title: 'Healthcare Access', prompt: 'Write about healthcare disparities. Include: your awareness, experiences, what you want to do, and commitment to change.', useCase: 'Advocacy' },
    { id: 'opt-long-14', title: 'Workforce Shortage', prompt: 'Address the optometry workforce shortage. Include: why this matters, where needs are greatest, your commitment to underserved, and action plans.', useCase: 'Workforce' },
    { id: 'opt-long-15', title: 'Technology in Optometry', prompt: 'Write about technology in eye care. Include: tech you\'ve used, how it improves care, your comfort with innovation, and vision for future.', useCase: 'Technology' },
    { id: 'opt-long-16', title: 'Collaboration', prompt: 'Write about working with other healthcare professionals. Include: experiences, what you learned about interprofessional care, and importance of collaboration.', useCase: 'Collaboration' },
    { id: 'opt-long-17', title: 'Cultural Competence', prompt: 'Describe your cultural competence journey. Include: training, experiences, specific situations, and ongoing learning.', useCase: 'Culture' },
    { id: 'opt-long-18', title: 'Pediatric Interest', prompt: 'Write about serving pediatric populations. Include: experiences with children, why pediatric optometry matters, and your approach.', useCase: 'Pediatric' },
    { id: 'opt-long-19', title: 'Geriatric Interest', prompt: 'Write about serving geriatric populations. Include: experiences with older adults, why geriatric care matters, and your approach.', useCase: 'Geriatric' },
    { id: 'opt-long-20', title: 'Why Our Program', prompt: 'Write why this specific program. Include: specific faculty, research, location, values alignment, and how you will contribute.', useCase: 'Program Specific' }
  ],
  faqs: [
    { question: 'How long should OptomCAS essays be?', answer: 'Follow prompts exactly. Typical limits: 4500 characters for personal statement. Count characters, not words.' },
    { question: 'Should I use the same essay for multiple schools?', answer: 'Customize for each school. Show you researched them.' },
    { question: 'What if I have low stats?', answer: 'Essays are your chance to shine. Focus on journey and fit.' },
    { question: 'Can I reuse my AMCAS for OptomCAS?', answer: 'No, they are different. Customize.' },
    { question: 'Should I address weaknesses?', answer: 'Briefly if needed. Focus on growth.' },
    { question: 'Who should read my essays?', answer: 'Pre-health advisors, students, mentors.' },
    { question: 'When should I start?', answer: 'Start early. 4-6 weeks before deadline.' },
    { question: 'What makes essays stand out?', answer: 'Specific stories, authentic voice, reflection.' }
  ],
  platformTips: [
    'Follow character limits exactly',
    'Use specific examples, not generic',
    'Show reflection and insight',
    'Proofread multiple times',
    'Have others review',
    'Customize for each school',
    'Avoid restating GPA/MCAT',
    'Let your authentic voice shine'
  ]
};