import { PromptPost } from './types';

export const writingPromptsKids: PromptPost = {
  slug: 'writing-prompts-kids',
  title: 'Writing Prompts for Kids: 50+ Fun Ideas to Spark Creativity (2026)',
  keyword: 'writing prompts for kids',
  description: '50+ creative writing prompts perfect for kids. Spark imagination and get kids writing for fun.',
  date: '2026-04-21',
  category: 'Kids',
  image: '/images/writing-prompts-kids.jpg',
  content: `<p>These fun <strong>writing prompts for kids</strong> make writing exciting. No pressure, just imagination!</p>`,
  shortPrompts: [
    { id: 'wk-1', prompt: 'Write about your favorite animal and why you love it', description: 'Favorite animal' },
    { id: 'wk-2', prompt: 'If you could have any superpower, what would it be and why?', description: 'Superpower' },
    { id: 'wk-3', prompt: 'What would you do if you found a treasure map?', description: 'Treasure map' },
    { id: 'wk-4', prompt: 'Describe your perfect day from morning to night', description: 'Perfect day' },
    { id: 'wk-5', prompt: 'If you could be any character from a book, who would you be?', description: 'Book character' },
    { id: 'wk-6', prompt: 'What do you want to be when you grow up? Why?', description: 'Dream job' },
    { id: 'wk-7', prompt: 'Write a story that starts with "One day..."', description: 'Story starter' },
    { id: 'wk-8', prompt: 'If you could have any pet, what would you pick?', description: 'Dream pet' },
    { id: 'wk-9', prompt: 'What is the best day you ever had? Tell about it.', description: 'Best day' },
    { id: 'wk-10', prompt: 'If you could go anywhere in the world, where would you go?', description: 'Dream place' },
    { id: 'wk-11', prompt: 'Write about a time you helped someone', description: 'Helping' },
    { id: 'wk-12', prompt: 'If you could have dinner with anyone, who would it be?', description: 'Dinner guest' },
    { id: 'wk-13', prompt: 'What is your favorite thing to do? Describe it.', description: 'Favorite thing' },
    { id: 'wk-14', prompt: 'If you could invent something, what would it be?', description: 'Invention' },
    { id: 'wk-15', prompt: 'What makes you special? What do people notice about you?', description: 'Special you' },
    { id: 'wk-16', prompt: 'Write about your best friend and why they are great', description: 'Best friend' },
    { id: 'wk-17', prompt: 'If you could be an animal for a day, which would you be?', description: 'Animal day' },
    { id: 'wk-18', prompt: 'What is the funniest thing that ever happened to you?', description: 'Funny story' },
    { id: 'wk-19', prompt: 'What would you do with one million dollars?', description: 'Million dollars' },
    { id: 'wk-20', prompt: 'Write about your family and what makes your family special', description: 'Family' },
    { id: 'wk-21', prompt: 'If you could live in any book, which would you pick?', description: 'Book world' },
    { id: 'wk-22', prompt: 'What is something you are really good at?', description: 'Good at' },
    { id: 'wk-23', prompt: 'If you could meet a famous person, who would it be?', description: 'Famous meet' },
    { id: 'wk-24', prompt: 'What is your favorite memory with your family?', description: 'Family memory' },
    { id: 'wk-25', prompt: 'Write about your happiest moment', description: 'Happy moment' }
  ],
  longPrompts: [
    { id: 'wk-long-1', title: 'Adventure Story', prompt: 'Write an adventure story: Where do you go? What happens? Who is with you? How does it end? Make it exciting! (Paragraphs)', useCase: 'Adventure' },
    { id: 'wk-long-2', title: 'Make Up a Creature', prompt: 'Design your own creature: What does it look like? Where does it live? What does it eat? Does it have powers? (Paragraphs)', useCase: 'Creature' },
    { id: 'wk-long-3', title: 'Magic Powers', prompt: 'You get magical powers for one day: What are they? How do you use them? Who do you help? (Paragraphs)', useCase: 'Magic' },
    { id: 'wk-long-4', title: 'Time Travel', prompt: 'You travel to the past or future: When do you go? What do you see? What do you learn? (Paragraphs)', useCase: 'Time Travel' },
    { id: 'wk-long-5', title: 'Friend Story', prompt: 'Write a story about two friends who go on an adventure. Who are they? What happens to them? (Paragraphs)', useCase: 'Friends' },
    { id: 'wk-long-6', title: 'Solve a Mystery', prompt: 'Something mysterious happened! Write what happened, who solved it, and how. (Paragraphs)', useCase: 'Mystery' },
    { id: 'wk-long-7', title: 'Dream House', prompt: 'Design your dream house: What does it look like? What rooms does it have? Who lives there with you? (Paragraphs)', useCase: 'Dream House' },
    { id: 'wk-long-8', title: 'Sports Story', prompt: 'Write about a big game or competition: What sport? Who played? How did you feel when you won or tried hard? (Paragraphs)', useCase: 'Sports' },
    { id: 'wk-long-9', title: 'Holiday Memory', prompt: 'Write about your favorite holiday: Which one? What did you do? Who was there? Why was it special? (Paragraphs)', useCase: 'Holiday' },
    { id: 'wk-long-10', title: 'Animal Adventure', prompt: 'Write a story from an animal\'s point of view: What animal? What happens to them? How do they feel? (Paragraphs)', useCase: 'Animal' },
    { id: 'wk-long-11', title: 'Superhero You', prompt: 'You are a superhero: What is your power? What is your costume? How do you help people? (Paragraphs)', useCase: 'Superhero' },
    { id: 'wk-long-12', title: 'Magic Object', prompt: 'You find a magic object: What is it? How does it work? What happens when you use it? (Paragraphs)', useCase: 'Magic Object' },
    { id: 'wk-long-13', title: 'Story Ending', prompt: 'Take this beginning and finish the story: "The door was locked. Suddenly, I heard a noise inside..." (Paragraphs)', useCase: 'Finish Story' },
    { id: 'wk-long-14', title: 'New Planet', prompt: 'You discover a new planet: What is it like? What lives there? What do you call it? (Paragraphs)', useCase: 'New Planet' },
    { id: 'wk-long-15', title: 'Best Birthday', prompt: 'Write about your best birthday: How old were you? What happened? Who was there? Why was it the best? (Paragraphs)', useCase: 'Birthday' },
    { id: 'wk-long-16', title: 'School Story', prompt: 'Write about your first day at a new school: How did you feel? Did you make friends? What happened? (Paragraphs)', useCase: 'School' },
    { id: 'wk-long-17', title: 'Kindness Story', prompt: 'Write about a time you were kind to someone: What did you do? How did they react? How did it make you feel? (Paragraphs)', useCase: 'Kindness' },
    { id: 'wk-long-18', title: 'Fairy Tale', prompt: 'Write your own fairy tale: There was once a... Who is the hero? What do they have to overcome? How do they win? (Paragraphs)', useCase: 'Fairy Tale' },
    { id: 'wk-long-19', title: 'Robot Story', prompt: 'You build a robot: What can it do? What is its name? What adventures do you have together? (Paragraphs)', useCase: 'Robot' },
    { id: 'wk-long-20', title: 'Ocean Adventure', prompt: 'You go on an underwater adventure: What do you see? What sea creatures do you meet? What do you discover? (Paragraphs)', useCase: 'Ocean' }
  ],
  faqs: [
    { question: 'How long should my story be?', answer: 'As long as you want. Both are great.' },
    { question: 'What if I do not know what to write?', answer: 'Point to a prompt.' },
    { question: 'Does it have to be perfect?', answer: 'No. Just write.' },
    { question: 'Can I draw pictures too?', answer: 'Absolutely.' },
    { question: 'Can I write about real things?', answer: 'Yes. Real experiences make great stories.' },
    { question: 'What if I run out of ideas?', answer: 'That is what prompts are for.' },
    { question: 'Should I write in order?', answer: 'You can. Whatever works.' },
    { question: 'Can I share my writing?', answer: 'Sharing is great.' }
  ],
  platformTips: [
    'Just write - don\'t worry about mistakes',
    'Use your imagination - there are no wrong answers',
    'Add lots of describing words',
    'Show how your characters feel',
    'Read your work out loud',
    'Ask "what happens next?"',
    'Have fun with it!',
    'Keep your writing in a special notebook'
  ]
};