import { PromptPost } from './types';

export const writingPromptsMiddleSchool: PromptPost = {
  slug: 'writing-prompts-middle-school',
  title: 'Writing Prompts for Middle School: 50+ Creative Ideas (2026)',
  keyword: 'writing prompts for middle school',
  description: 'Creative writing prompts for middle school students.',
  date: '2026-04-21',
  category: 'Education',
  image: '/images/writing-prompts-middle-school.jpg',
  content: `<p>These <strong>middle school writing prompts</strong> help students develop creativity and writing skills while having fun.</p>`,
  shortPrompts: [
    { id: 'ms-1', prompt: 'Write about your dream pet and why you want it', description: 'Dream pet' },
    { id: 'ms-2', prompt: 'Describe your perfect day from start to finish', description: 'Perfect day' },
    { id: 'ms-3', prompt: 'What would you do with a time machine?', description: 'Time travel' },
    { id: 'ms-4', prompt: 'Write a story starting with The door opened and...', description: 'Story starter' },
    { id: 'ms-5', prompt: 'If you could have any superpower, what would it be?', description: 'Superpower' },
    { id: 'ms-6', prompt: 'Describe your best friend. What makes them special?', description: 'Best friend' },
    { id: 'ms-7', prompt: 'What if animals could talk? What would they say?', description: 'Talking animals' },
    { id: 'ms-8', prompt: 'Write about a time you helped someone', description: 'Helping others' },
    { id: 'ms-9', prompt: 'What do you want to be when you grow up?', description: 'Future career' },
    { id: 'ms-10', prompt: 'Describe your favorite place in the world', description: 'Favorite place' },
    { id: 'ms-11', prompt: 'What is the best advice someone gave you?', description: 'Best advice' },
    { id: 'ms-12', prompt: 'Write about a mysterious box you found', description: 'Mystery box' },
    { id: 'ms-13', prompt: 'What would your life be like on another planet?', description: 'Space life' },
    { id: 'ms-14', prompt: 'Describe your favorite meal and how to make it', description: 'Favorite food' },
    { id: 'ms-15', prompt: 'Write a letter to your future self', description: 'Future letter' },
    { id: 'ms-16', prompt: 'What makes you unique?', description: 'What makes me me' },
    { id: 'ms-17', prompt: 'Describe a magical object you found', description: 'Magic object' },
    { id: 'ms-18', prompt: 'What rules would you make if you were president?', description: 'President rules' },
    { id: 'ms-19', prompt: 'Write about your greatest adventure', description: 'Greatest adventure' },
    { id: 'ms-20', prompt: 'What do you think happens after death?', description: 'Big questions' },
    { id: 'ms-21', prompt: 'Describe a world where dreams come true', description: 'Dream world' },
    { id: 'ms-22', prompt: 'What is your happiest memory?', description: 'Happy memory' },
    { id: 'ms-23', prompt: 'Write about meeting your favorite celebrity', description: 'Celebrity meet' },
    { id: 'ms-24', prompt: 'What would you do with one million dollars?', description: 'Million dollars' },
    { id: 'ms-25', prompt: 'Describe the best gift you ever received', description: 'Best gift' }
  ],
  longPrompts: [
    { id: 'ms-long-21', title: 'Adventure Story', prompt: 'Write a 5-paragraph adventure story. Include: setting, problem, 3 events, solution, ending. Make it exciting!', useCase: 'Adventure Fiction' },
    { id: 'ms-long-2', title: 'Personal Narrative', prompt: 'Write about an important moment in your life. Include: hook, details, feelings, what you learned.', useCase: 'Personal Narrative' },
    { id: 'ms-long-3', title: 'Opinion Essay', prompt: 'Write an opinion essay: state your opinion, give 3 reasons, examples for each, conclusion.', useCase: 'Opinion Writing' },
    { id: 'ms-long-4', title: 'Research Report', prompt: 'Choose an animal. Report: habitat, diet, predators, interesting facts, why it matters. 5 paragraphs.', useCase: 'Research Report' },
    { id: 'ms-long-5', title: 'How-To Guide', prompt: 'Write how-to guide: hobby, materials, steps minimum 8, tips, conclusion. Teach others!', useCase: 'How-To' },
    { id: 'ms-long-6', title: 'Fantasy Story', prompt: 'Write fantasy story with magical world. Include: character, problem, magical help, resolution.', useCase: 'Fantasy Fiction' },
    { id: 'ms-long-7', title: 'Book Review', prompt: 'Write book review: title, author, summary no spoilers, your opinion, recommend?', useCase: 'Book Review' },
    { id: 'ms-long-8', title: 'Compare Essay', prompt: 'Compare two things: similarities 3, differences 3, which you prefer and why.', useCase: 'Compare/Contrast' },
    { id: 'ms-long-9', title: 'Biography', prompt: 'Write about a famous person: early life, achievements, challenges, legacy, why inspiring.', useCase: 'Biography' },
    { id: 'ms-long-10', title: 'Mystery Story', prompt: 'Write mystery with clues, detective, twist ending. Keep readers guessing!', useCase: 'Mystery Fiction' },
    { id: 'ms-long-11', title: 'Speech', prompt: 'Write 2-minute speech: attention getter, 3 points, memorable ending. Practice out loud!', useCase: 'Speech' },
    { id: 'ms-long-12', title: 'Science Fiction', prompt: 'Write sci-fi: future setting, technology, problem, solution. Think big!', useCase: 'Sci-Fi' },
    { id: 'ms-long-13', title: 'Poetry Collection', prompt: 'Write 3 poems: one about nature, one about feelings, one fun. Different styles!', useCase: 'Poetry' },
    { id: 'ms-long-14', title: 'Letter to Editor', prompt: 'Write letter about something in your community: problem, solution, call to action.', useCase: 'Persuasive Letter' },
    { id: 'ms-long-15', title: 'Short Story', prompt: 'Write short story: character development, conflict, climax, resolution. Show, do not tell!', useCase: 'Short Story' },
    { id: 'ms-long-16', title: 'Diary Entries', prompt: 'Write 3 diary entries: same day, different mood. Show how feelings change over time.', useCase: 'Diary' },
    { id: 'ms-long-17', title: 'Movie Review', prompt: 'Write movie review: summary, what you liked, what you did not, star rating, who would enjoy.', useCase: 'Review' },
    { id: 'ms-long-18', title: 'Historical Fiction', prompt: 'Write story set in past. Research first: accurate setting, realistic characters.', useCase: 'Historical Fiction' },
    { id: 'ms-long-19', title: 'Comic Script', prompt: 'Write comic strip: 4 panels minimum, dialogue, action, humor or adventure.', useCase: 'Comic Writing' },
    { id: 'ms-long-20', title: 'Free Choice', prompt: 'Write anything you want! No rules, just write what excites you.', useCase: 'Free Write' }
  ],
  faqs: [
    { question: 'How long should my writing be?', answer: 'Quality over quantity. Short prompts: 1-2 paragraphs. Long prompts: 3-5 paragraphs.' },
    { question: 'What if I do not know what to write?', answer: 'Start anywhere. I do not know is still writing! Pick a prompt that calls to you.' },
    { question: 'Can I type these instead of handwriting?', answer: 'Absolutely. Typing is great for building keyboard skills and makes editing easier.' },
    { question: 'Does it have to be perfect?', answer: 'No. First drafts are supposed to be messy. Just write, edit later.' },
    { question: 'What if I run out of ideas?', answer: 'That is when prompts help. Pick randomly or close your eyes and point.' },
    { question: 'Should I share my writing?', answer: 'Sharing is optional but helpful. Family, friends, or teacher: whoever feels safe.' },
    { question: 'Can I use first person?', answer: 'Yes. Especially for personal writing. Your voice matters.' },
    { question: 'What makes writing good?', answer: 'Clear ideas, descriptive words, and honesty. That is it.' }
  ],
  platformTips: [
    'Write a little bit every day: even 10 minutes helps',
    'Read lots of books to see how good writers work',
    'Use sensory details: what do you see, hear, smell, feel, taste?',
    'Show characters through actions, not just telling',
    'Read your writing aloud to catch mistakes',
    'Do not erase, just cross out and keep writing',
    'Get feedback from trusted readers',
    'Keep your writing in a special folder or notebook'
  ]
};